Performance improvements
SeleniumHQ/selenium pull request #10105
Opened 2021-11-30 13:17 UTC by larrydiamond

### Description
These changes are purely performance improvements to make Selenium run faster, there are no new features in this pull request.

### Motivation and Context
These changes provide performance improvements only.   The uses of StringBuffer below can be safely replaced with StringBuilder and avoid synchronization overhead.   The change to use equalsIgnoreCase is faster and reduces memory consumption by eliminating many temporary strings.

### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist
- [X ] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ X] All new and existing tests passed.

2021-11-30 13:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SeleniumHQ/selenium?pullRequest=10105) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SeleniumHQ/selenium?pullRequest=10105) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SeleniumHQ/selenium?pullRequest=10105) it.</sub>

2021-12-01 14:29 UTC, diemol requested changes
@larrydiamond, thank you for this PR. However, we are not making any changes under the `thoughtworks` package name because it a legacy package and some code is deprecated. This willl be eventually phased out.

If you wish, please keep the change to `Platform.java` only and then I can merge this PR.

2021-12-01 23:59 UTC, larrydiamond commented
Done.

2021-12-02 10:36 UTC, diemol approved these changes
Thank you, @larrydiamond!
Congrats on your first contribution! 🎉

2021-12-02 10:36 UTC, merged