[java] Adds new desktop cast command for Chromium #10190
SeleniumHQ/selenium pull request #10191
Opened 2021-12-27 18:36 UTC by gpt14

### Description
Adds new desktop cast command for Chromium as detailed in #10182

### Motivation and Context
#10182 

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2021-12-27 20:26 UTC, titusfortner requested changes
Nice! Thanks for this. I thought I was going to have to do this all later this week. Appreciate the work.

The only request is I think we should keep the convention of the other constants and use: `START_CAST_DESKTOP_MIRRORING`, even though it is longer.

2021-12-29 05:40 UTC, gpt14 commented
Thanks, @titusfortner. I have renamed the constant to START_CAST_DESKTOP_MIRRORING

2021-12-29 17:11 UTC, titusfortner approved these changes

2021-12-29 17:13 UTC, merged

2021-12-29 17:13 UTC, titusfortner commented
Excellent! Thanks for the submission!