Remove opera class from Python codebase
SeleniumHQ/selenium pull request #10470
Opened 2022-03-23 10:24 UTC by nienkenijkamp

**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description
Remove the Opera class from the Python codebase. The Opera classes in Java were already marked as Deprecated. 

### Motivation and Context
Opera does not support W3C, and therefore it should be deleted from Selenium. Issue #10379.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2022-03-23 10:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SeleniumHQ/selenium?pullRequest=10470) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SeleniumHQ/selenium?pullRequest=10470) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SeleniumHQ/selenium?pullRequest=10470) it.</sub>

2022-04-14 06:40 UTC, symonk commented
Thanks @nienkenijkamp a quick look and python has a few other references for opera:

```console
opera_options_tests.py
new_session_tests.py
setup.py (not sure if we are utilising setuptools fully but we should remove it from there too
```

2022-04-17 12:23 UTC, symonk requested changes
some test code still needs updated here to support opera removal

2022-05-10 17:37 UTC, titusfortner commented
Thank you for your submission, there are more changed required than just this, so closing in favor of #10630

2022-05-10 17:37 UTC, closed without merging