[rb] - Improving Wait class error handling
SeleniumHQ/selenium pull request #10659
Opened 2022-05-17 08:50 UTC by luke-hill

### Description
When re-polling during the `Wait#until` method. Ensure we don't trip up if the element is missing **OR** if the element is stale, as both are equally likely

### Motivation and Context
During the upgrade from capybara 3.35 to 3.37.1 this error starts showing a **lot** more. It is likely that as we are moving faster in better rubies, we are likely to hit that split second where the web element could be missing OR it could be in the process of appearing / changing and therefore register as stale.

I've classified this as a bugfix. As ideally missing element and stale element should live hand in hand.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [ ] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-05-17 13:19 UTC, titusfortner requested changes
What I think the other bindings do is to make this configurable. I think the right answer here is to give ignored an attr accessor, so user can set it if they want.

2022-05-17 13:33 UTC, luke-hill commented
I shall do that.

2022-05-17 13:42 UTC, luke-hill commented
Notwithstanding your point, which I agree with, are the defaults here meaningful / valid? Or should we amend them?

2022-06-23 03:46 UTC, titusfortner commented
I just noticed that you can set the list of exceptions to ignore as part of the initialization of the Wait. That should be sufficient for configuration.

2022-06-23 03:46 UTC, closed without merging

2022-06-23 08:59 UTC, luke-hill commented
I think the issue was more should we amend the default exceptions. But yeh we never reached a consensus here.

Imo we should edit the default exceptions, as both are equally likely.

2022-07-05 12:20 UTC, titusfortner commented
No, we were never going to change the default away from just the `NoSuchElementError`, just like all the other language bindings. A stale element isn't going to become un-stale, so additional logic would be necessary for that to remotely make sense; it definitely should not be ignored by default.

2022-07-05 13:02 UTC, luke-hill commented
FYI That isn't true. As if you re-find something it can then not be stale. But given we didn't reach a consensus this can just be considered dead. Same as the logic for finding the element can also fail and then not fail under the same test conditions.