Use `which()` to get Firefox path on Mac OS
SeleniumHQ/selenium pull request #10818
Opened 2022-06-27 10:07 UTC by bogdancondurache

Fixes #10686

### Description
The Firefox binary under Mac OS was using a hardcoded path. This was
failing when trying to manipulate PATH env var to use Firefox from a
different location or if Firefox was installed in a different place.

### Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [X] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

2022-06-27 10:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SeleniumHQ/selenium?pullRequest=10818) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SeleniumHQ/selenium?pullRequest=10818) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SeleniumHQ/selenium?pullRequest=10818) it.</sub>

2022-06-27 20:32 UTC, symonk submitted a review, later dismissed

2022-06-27 20:33 UTC, symonk commented on py/selenium/webdriver/firefox/firefox_binary.py
> +            start_cmd = self.which(ffname)
is `ffname` in scope here?

2022-06-27 21:09 UTC, symonk requested changes
referencing a local variable that doesn't exist

2022-06-27 21:16 UTC, bogdancondurache commented on py/selenium/webdriver/firefox/firefox_binary.py
> +            start_cmd = self.which(ffname)
yes, my bad, totally missed that. I assigned ffname to "firefox" only because from what I found iceweasel is not even available for Mac OS

2022-06-27 21:24 UTC, symonk approved these changes

2022-06-27 21:24 UTC, symonk commented on py/selenium/webdriver/firefox/firefox_binary.py
> +            start_cmd = self.which(ffname)
interesting, from what I can find too `iceweasel` is not supported on `osx` too; one for another ticket tho - Thanks

2022-06-28 15:44 UTC, symonk approved these changes

2022-06-29 07:22 UTC, diemol approved these changes
Thank you, @bogdancondurache!

2022-06-29 07:22 UTC, merged