update docs for PointerActions#move_to
SeleniumHQ/selenium pull request #10872
Opened 2022-07-13 17:21 UTC by mockdeep

`move_to` has been changed to start from the center of the element rather than the top-left corner.

### Checklist
- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-07-13 17:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/SeleniumHQ/selenium?pullRequest=10872) <br/>All committers have signed the CLA.

2022-07-13 17:54 UTC, titusfortner requested changes
Thank you for this PR! 

The only issue with it now is that it isn't always the "center" of the element, but is technically the ["in-view center point"](https://w3c.github.io/webdriver/#dfn-center-point) of the element.

But that's a lot to put in the places you updated. Maybe we just change "middle" to "in-view center point" on line 71 & delete line 72 which isn't exactly correct either?

2022-07-13 22:14 UTC, mockdeep commented
@titusfortner is this more along the lines of what you were thinking?

2022-07-14 14:36 UTC, titusfortner approved these changes

2022-07-14 14:37 UTC, merged

2022-07-14 14:37 UTC, titusfortner commented
yes, thanks!