Fix issue #10908. But the Grid crash issue need to be fix to merge this.
SeleniumHQ/selenium pull request #10911
Opened 2022-07-28 14:26 UTC by ketanvj

Commented code that checks for service is not available. So that grid default timeouts and retries kicks-in.

**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

### Motivation and Context

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [ ] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-07-28 14:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SeleniumHQ/selenium?pullRequest=10911) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SeleniumHQ/selenium?pullRequest=10911) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SeleniumHQ/selenium?pullRequest=10911) it.</sub>

2022-08-01 05:12 UTC, pujagani requested changes
I appreciate your help. However, this might not be the right approach.  I understand the error occurs while throwing the ConfigException. But as far as I understand, issue #10908 aims to ensure the server attempts to retry first and then throws an error when retries are exhausted. I suggest please discuss on the same Github issue regarding the right approach and proceed accordingly.

2022-08-01 05:52 UTC, ketanvj commented
Thanks @pujagani. This was analyzed as a group in our session on 29th Jul with @diemol.  I am open to taking this up and analyzing this further if someone can guide me.  Closing this for now.

2022-08-01 05:52 UTC, closed without merging

2022-08-01 08:02 UTC, diemol commented
@ketanvj yes, I need to check the bug we discovered while fixing this issue. When I have fixed that, I will comment in the issue. Thank you.

2022-08-03 08:19 UTC, diemol commented
@ketanvj apologies, I forgot about this PR and I already pushed a fix for the feature request. Sorry!