[java] Remove Opera related classes
SeleniumHQ/selenium pull request #10950
Opened 2022-08-16 13:53 UTC by pujagani

**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

Related to #10379 for Java.

### Motivation and Context

Opera does not support w3c. The Opera related driver and options class was deprecated more than 2 versions before. Now removing the support.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [X] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

2022-08-16 14:49 UTC, titusfortner approved these changes

2022-08-17 09:55 UTC, diemol requested changes, later dismissed
Can you please remove it from the https://github.com/SeleniumHQ/selenium/blob/trunk/Rakefile too?

Thank you!

2022-08-17 10:24 UTC, pujagani commented
Thank you for bringing it to my notice. Totally missed that one.

2022-08-18 02:32 UTC, SuhailFluke approved these changes

2022-08-18 08:00 UTC, merged