Fix frame_to_be_available_and_switch_to_it() for string inputs
SeleniumHQ/selenium pull request #10967
Opened 2022-08-21 14:14 UTC by mdmintz

Fix ``frame_to_be_available_and_switch_to_it()`` for string inputs.
* This resolves https://github.com/SeleniumHQ/selenium/issues/10963

### Description
Fix ``frame_to_be_available_and_switch_to_it()`` for string inputs. Currently, it only works with numeric inputs (see https://github.com/SeleniumHQ/selenium/issues/10963 for details)

### Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [X] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have added tests to cover my changes.
- [X] All new tests passed. Existing tests that were passing are still passing.

2022-08-21 16:14 UTC, symonk requested changes

2022-08-21 16:14 UTC, symonk commented on py/CHANGES
> +Selenium 4.4.4
:+1: Thanks - not sure if worthy of a patch release, likely be part of `4.5.0`? will let the folks decide that one!

2022-08-21 16:14 UTC, symonk commented on py/selenium/webdriver/support/expected_conditions.py
> +            if hasattr(locator, '__iter__') and type(locator) is not str:
I think we should try:

 - getting an iterator from locator using `iter(locator)` to support old style iterator protocol via `__getitem__` (if locator is not a str)

2022-08-21 16:14 UTC, symonk commented on py/selenium/webdriver/support/expected_conditions.py
> +            if hasattr(locator, '__iter__') and type(locator) is not str:
why `type(locator) is not str`, seems closed for extension, `not isinstance(locator, str)` seems more appropriate, wouldn't be unheard of for some people to subclass strings as rare as that might be we'd be unfairly limiting users and violating liskov on their behalf

2022-08-21 16:14 UTC, symonk commented on py/test/selenium/webdriver/common/frame_switching_tests.py
> +def test_frame_to_be_available_and_switch_to_it_using_string_inputs(driver, pages):
is there existing test for non str iterables successfully unpacked to `find_element(...)` (if not could we add one)

2022-08-21 21:37 UTC, mdmintz commented on py/test/selenium/webdriver/common/frame_switching_tests.py
> +def test_frame_to_be_available_and_switch_to_it_using_string_inputs(driver, pages):
The test added was the missing link to why the bug happened in the first place. Looks like the other areas are covered.

2022-08-21 21:39 UTC, mdmintz commented on py/CHANGES
> +Selenium 4.4.4
For a small fix like this, ``4.4.4`` could buy some time until the bigger ``4.5.0`` release is ready.

2022-08-21 21:57 UTC, mdmintz commented on py/selenium/webdriver/support/expected_conditions.py
> +            if hasattr(locator, '__iter__') and type(locator) is not str:
Updated in new commit.

2022-08-22 09:20 UTC, diemol requested changes
Left some comments.

2022-08-22 09:20 UTC, diemol commented on py/BUILD.bazel
> +SE_VERSION = "4.4.4"
This does not need to be bumped yet.

2022-08-22 09:20 UTC, diemol commented on py/CHANGES
> +Selenium 4.4.4
We are releasing 4.5.0 next week, so not sure if we will release 4.4.4

2022-08-22 09:20 UTC, diemol commented on py/selenium/__init__.py
> +__version__ = "4.4.4"
Please do not bump the version as we do not know if this will be 4.4.4 or 4.5.0

2022-08-22 09:20 UTC, diemol commented on py/selenium/webdriver/__init__.py
> +__version__ = '4.4.4'
Please do not bump the version as we do not know if this will be 4.4.4 or 4.5.0

2022-08-22 09:20 UTC, diemol commented on py/setup.py
> +    'version': "4.4.4",
Please do not bump the version as we do not know if this will be 4.4.4 or 4.5.0

2022-08-22 10:28 UTC, diemol reviewed
CI is passing, we just need to revert the version changes to merge.

2022-08-22 12:56 UTC, diemol approved these changes
Thank you, @mdmintz!

2022-08-22 12:59 UTC, merged