Fixed some typos
SeleniumHQ/selenium pull request #11035
Opened 2022-09-15 16:23 UTC by shishurajpandey

**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

Just a minor code improvement, doesn't affect functionality.

### Description

Just a minor code improvement, doesn't affect functionality.

### Checklist

- [x ] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x ] All new and existing tests passed.

2022-09-15 16:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SeleniumHQ/selenium?pullRequest=11035) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SeleniumHQ/selenium?pullRequest=11035) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SeleniumHQ/selenium?pullRequest=11035) it.</sub>

2022-09-15 19:40 UTC, titusfortner requested changes
Thanks for the submission! "behavior" is correct for US English; "behaviour" is British English.

2022-09-15 19:40 UTC, titusfortner commented on java/src/com/thoughtworks/selenium/Selenium.java
> +   * header. This only works if the browser is configured to use the builtin Selenium proxy.
built-in

2022-09-15 22:14 UTC, shishurajpandey commented on java/src/com/thoughtworks/selenium/Selenium.java
> +   * header. This only works if the browser is configured to use the builtin Selenium proxy.
Resolved.

2022-09-16 03:49 UTC, titusfortner commented
Ran a basic search in the project because I was curious
behaviour - 536 times
behavior - 3200 times

Let's not change those, ok?

2022-09-16 08:43 UTC, shishurajpandey commented
> Ran a basic search in the project because I was curious behaviour - 536 times behavior - 3200 times
> 
> Let's not change those, ok?

Sure.

2022-09-25 20:29 UTC, titusfortner approved these changes

2022-09-25 20:29 UTC, merged