[ruby][bidi] Add filtering capability to LogInspector
SeleniumHQ/selenium pull request #11508
Opened 2023-01-03 18:25 UTC by TamsilAmani

### Description

Add filtering capability to LogInspector

### Motivation and Context

Allow users to filter logs based on log level

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2023-01-03 19:27 UTC, titusfortner commented on rb/spec/integration/selenium/webdriver/bidi/log_inspector_spec.rb
> +      describe LogInspector, exclusive: {browser: %i[firefox]} do
Use `only` instead of `exclusive`

2023-01-05 07:58 UTC, TamsilAmani commented on rb/spec/integration/selenium/webdriver/bidi/log_inspector_spec.rb
> +      describe LogInspector, exclusive: {browser: %i[firefox]} do
Changes committed

2023-01-15 01:57 UTC, titusfortner requested changes
When I merged the PR into trunk, I might have done the guards incorrectly? Either way a bunch of tests aren't passing. Do we just need to remove the guards that don't need to be there?

2023-01-15 01:57 UTC, titusfortner commented on rb/spec/integration/selenium/webdriver/bidi/log_inspector_spec.rb
> +    class BiDi # rubocop:disable Metrics/ClassLength
let's add this file path to the exclude list in .rubocop.yml instead of in the code here.

2023-01-15 01:57 UTC, titusfortner commented on rb/spec/integration/selenium/webdriver/bidi/log_inspector_spec.rb
>            @page = '/bidi/logEntryAdded.html'
for this, we should prefer `let` instead of setting an instance variable in a before hook: `let(:page) { '/bidi/logEntryAdded.html' }`

2023-01-16 07:44 UTC, TamsilAmani commented
Yes @titusfortner the current guards are not working as expected. For example, I have stopped all tests from being run on chrome using the `except` hook. But one of the tests failed in chrome instead of being pending. Here's the error.

```
Expected example to fail since it is pending, but it passed.

  0) Selenium::WebDriver::BiDi::LogInspector can filter console log FIXED
     Expected pending 'Test guarded; no reason given' to fail. No error was raised.
     # ./spec/integration/selenium/webdriver/bidi/log_inspector_spec.rb:98
```

That's why I preferred to use the `exclusive` hook. This problem doesn't happen with it.

2023-01-16 14:54 UTC, titusfortner commented
If it's passing as pending that means that the feature being tested works in Chrome. Is it implemented or does the test not test the right thing?

2023-01-16 20:11 UTC, TamsilAmani commented
@titusfortner This is long but insightful.

Alright, so I got to know why some tests are failing in chrome. I'll brief it out in points.

1. It seems that Chrome has implemented BiDi to some extent. So, the tests which were supposed to fail in chrome earlier are now passing. [**RESULT** = 8/12 PASS, 4/12 PENDING]

2. The 4 tests which are pending in chrome are all related to the **`console logs`** generated from the browser. Let's take an example for the response returned when there's a console log in both chrome and firefox.

In Chrome,
`#<Selenium::WebDriver::BiDi::ConsoleLogEntry:0x0000000111a5ed78 @level="info", @text="Hello, world!", @timestamp=1673896631113.0, @stack_trace={"callFrames"=>[{"columnNumber"=>20, "functionName"=>"helloWorld", "lineNumber"=>16, "url"=>"http://localhost:8180//bidi/logEntryAdded.html"}, {"columnNumber"=>51, "functionName"=>"onclick", "lineNumber"=>6, "url"=>"http://localhost:8180//bidi/logEntryAdded.html"}]}, @type="console", @method="log", @realm=nil, @args=[{"type"=>"string", "value"=>"Hello, world!"}]>`

In Firefox,
`#<Selenium::WebDriver::BiDi::ConsoleLogEntry:0x000000012e0e3060 @level="info", @text="Hello, world!", @timestamp=1673896425144, @stack_trace=nil, @type="console", @method="log", @realm=nil, @args=[{"type"=>"string", "value"=>"Hello, world!"}]>`

As you can see, chrome returns **@stack_trace** which is **NOT NULL** while firefox returns @stack_trace which is **NULL**. Hence, a test to check `stack_trace == empty` will pass in firefox but fail in chrome.

This is what is causing the 4 tests to be pending. The response for console log is different in chrome and firefox. It is mainly due to the `stack_trace` property but there's another change in which **_chrome is returning a @realm and firefox isn't_** but this is not causing any trouble as of now.

**NOTE:**
- I couldn't find the right response which must be returned in case of console log (mainly the `stack_trace` property) on the w3c page. https://w3c.github.io/webdriver-bidi/#intro
- The CI will pass now most probably with 8 PASSING and 4 PENDING in chrome. There's no failure now. 

What do you suggest? :)

2023-01-25 10:39 UTC, TamsilAmani commented
Based on my understanding of the [WPT tests](https://github.com/web-platform-tests/wpt/blob/e81901f6539c378f6f6010f988358a84b5abea52/webdriver/tests/bidi/log/entry_added/stacktrace.py#L12-L13) which @whimboo pointed out in tlc group, I think that when `log level = info`, we don't expect a stack trace and when `log level = error`, we expect it.
This condition is correctly implemented in firefox but not in chrome as it gives a stack trace with level = info too. Hence, I've modified the tests to exclude chrome. Any further insights on this would be helpful.

2023-01-25 16:42 UTC, titusfortner approved these changes

2023-02-13 17:10 UTC, merged