issue-1533899181
SeleniumHQ/selenium pull request #11551
Opened 2023-01-15 16:55 UTC by RussiaVk

solve array ClassCastException

**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

### Motivation and Context

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [ ] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-01-15 16:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SeleniumHQ/selenium?pullRequest=11551) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SeleniumHQ/selenium?pullRequest=11551) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SeleniumHQ/selenium?pullRequest=11551) it.</sub>

2023-01-15 21:13 UTC, diemol requested changes
Can you please add a test case to verify this?

2023-01-15 21:35 UTC, diemol requested changes
@RussiaVk, seems this PR is not compiling?

2023-01-17 08:21 UTC, RussiaVk commented
> Can you please add a test case to verify this?

Hi,reproduce code here:
[](https://github.com/SeleniumHQ/selenium/issues/11550)

2023-01-17 09:02 UTC, diemol requested changes
Can you please add the code to reproduce as a test so we can always check that this does not break? In the meantime I will let the CI run.

2023-01-17 10:05 UTC, RussiaVk commented
> Can you please add the code to reproduce as a test so we can always check that this does not break? In the meantime I will let the CI run.

```
import java.io.IOException;
import org.junit.Test;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;

public class Reproduce {
	@Test
	public void test() throws IOException {
		var driver = new ChromeDriver(new ChromeOptions().setHeadless(true));
		String content = "var a0_0x36afd3=a0_0x3a21;function a0_0x3a21(n,t){var B=a0_0x2403();return(a0_0x3a21=function(n,t){return B[n-=151]})(n,t)}function QBLnx(){}function getTrack(n,t,B){return window.get_func(window.get_track(n),t,B)}function get_aa(n,t,B){return getTrack(n,t,B)}function a0_0x2403(){var n=[\"$_HFHC\",\"$_BICCH\",\"$_DACv\",\"charCodeAt\",\"$_BFFCl\",\"$_CBJCl\",\"$_BHEHl\",\"$_CGJHG\",\"$_BDGCU\",\"$_CCGCJ\",\"$_BAJCX\",\"$_BIBHs\",\"$_CIHn\",\"$_BGBCu\",\"$_CHIHu\",\"$_CJECz\",\"$_BFECN\",\"$_EEHe\",\"$_CBFCD\",\"$_BBCCd\",\"$_CCACU\",\"getM\",\"$_CJCHG\",\"$_BDFCJ\",\"$_CHAHO\",\"$_CBCCC\",\"$_BFIHB\",\"$_CJICH\",\"$_BDDHv\",\"$_CBHHV\",\"$_BHBHI\",\"$_BFACt\",\"$_HGHv\",\"$_CAHCs\",\"$_DIHu\",\"$_FDU\",\"$_BIEHS\",\"get_aa\",\"$_CIAHX\",\"$_CBAHf\",\"fromCharCode\",\"$_EDHb\",\"$_EBCg\",\"$_BDAHc\",\"$_CGCCE\",\"$_BAEHb\",\"$_CCECC\",\"$_BDGHO\",\"$_GBCH\",\"$_JBHZ\",\"$_BFEHQ\",\"$_CCJHp\",\"$_CAGCq\",\"$_BADCi\",\"$_JFHe\",\"$_EIHq\",\"$_CFHCZ\",\"$_FDHS\",\"$_CDHCH\",\"$_HBHW\",\"$_CDJHa\",\"$_BGDHQ\",\"$_JIHD\",\"$_HICu\",\"$_BBDHM\",\"$_BHGCF\",\"$_IBHi\",\"$_CADCA\",\"$_CFJCy\",\"$_CIIHF\",\"$_BCHHl\",\"$_GBHF\",\"$_CDFCm\",\"$_IFCh\",\"$_BGBHS\",\"$_IIHz\",\"$_CCFCe\",\"$_BCDH_\",\"$_DGCk\",\"$_BIICR\",\"$_CIBHQ\",\"$_BCJHx\",\"$_CGFHO\",\"$_CAIHz\",\"$_IDCz\",\"$_CHEHW\",\"$_CEDCW\",\"$_CGICw\",\"$_CJBCa\",\"$_BBAHg\",\"$_DAECw\",\"$_ICCC\",\"$_BFCHi\",\"$_HDCd\",\"use strict\",\"$_EICI\",\"8525doWseu\",\"$_BHIHe\",\"$_BJJHu\",\"$_CJFHA\",\"$_CJJCo\",\"$_BHHCd\",\"$_BFHHR\",\"$_BDEHl\",\"apply\",\"$_BGECM\",\"$_BP\",\"$_BCDCs\",\"$_CEBCM\",\"$_EHCA\",\"$_CBACL\",\"getV_encrypt\",\"$_CFFHP\",\"$_CABHP\",\"$_CFBHZ\",\"$_JEHw\",\"$_DBHGJ\",\"$_CGBHz\",\"$_CDICt\",\"$_CFECv\",\"$_CFHHb\",\"$_HFCc\",\"$_JBCA\",\"$_FHCv\",\"$_CIFCb\",\"$_HEHF\",\"$_CGBCV\",\"$_CCFHI\",\"$_BCFCL\",\"$_CFCCK\",\"$_FGHm\",\"$_CIEHV\",\"$_BJEHn\",\"$_CIACL\",\"$_BAECG\",\"$_GFHq\",\"$_BEHCE\",\"$_BHACC\",\"concat\",\"$_BEJHJ\",\"$_CDHHq\",\"$_Db\",\"$_DDCv\",\"$_CJIHk\",\"$_CHGCK\",\"$_CIJCE\",\"$_BGIHb\",\"$_DBGGT\",\"$_BGHHp\",\"length\",\"$_CCICb\",\"$_BECCy\",\"$_BFJHm\",\"$_BEACL\",\"$_IAHY\",\"$_FCHm\",\"$_BDJCM\",\"$_CABCa\",\"$_FGCa\",\"$_DFCw\",\"$_BGEHq\",\"$_DAAHb\",\"$_FEHN\",\"$_DAHCP\",\"$_BFFHp\",\"$_CDACb\",\"$_CDCC_\",\"$_BJGCH\",\"$_CGGCb\",\"$_CJFCP\",\"$_DAACe\",\"$_CAACZ\",\"$_BCAHx\",\"3156tVYfhD\",\"$_BHFCf\",\"$_GHCc\",\"$_HBCp\",\"userResponse\",\"$_BJECK\",\"$_CGAHe\",\"$_GJHN\",\"$_IBCC\",\"$_BGDCN\",\"$_BJCCv\",\"$_IHCn\",\"$_BBJCB\",\"$_BABHI\",\"encrypt\",\"$_BAGHU\",\"$_JDHg\",\"$_CEJHx\",\"$_BCEHh\",\"$_EBHi\",\"$_BHICq\",\"$_GHHO\",\"1664658NPRWCo\",\"$_IGCi\",\"$_BCGCJ\",\"function\",\"$_CGHHE\",\"$_BIECZ\",\"$_CJGCf\",\"$_JECw\",\"$_DJHO\",\"$_BFBCa\",\"$_BABCU\",\"$_BFDCn\",\"$_DEHS\",\"$_HHCD\",\"$_CCBCx\",\"$_CFDCR\",\"%0D%1C6%1Dv=%0A%1D%3C%1Dw0%1D%064%07%5D%06%17%01?%00H%3C&%086%1Bd7%16%1B;1%5C*%14G%0D%02Z?&F%0D%E9%84%A2%E7%BD%87%E5%8E%9A%E6%94%88%08'%E6%9D%A6%E8%AF%86%EF%BD%82%E8%AE%8F%E6%A2%AF%E6%9E%B6%E5%89%B2%E5%A7%A2%E5%8D%8E%E6%96%8E%E4%BD%8F%E5%84%B6%E7%9B%AB%E9%85%A4%E7%BC%B6%E5%8E%BA%E6%94%9F4%1B%EF%BC%A1%E5%AE%A1%E5%BB%AC%E7%95%9C%E8%AE%A4%E6%96%99%E7%9A%AD%11%3C%EF%BD%A6%0D%0A%5B*%17%1D%0D%0BH,%19U:%02H?%1D@$%0AK(C%0D2%1CLnLC%06%04E%1F*%06g.h%19:7%01:c%09.%03%12%5B%7D%1B=.%12.h.9:%12.l%1A@%18%12%06d/9%08%00%3Cg,%0B%0A%7C%0Cq2%00%16%10,D*!!%04?%5E50=%1BVC/5.%0D%1C%5D9%0C%1A%201%E4%BC%89%E7%BA%81%E5%91%BC%E5%9A%B1%E8%B1%90%E7%9B%AB%E5%8F%AB%E6%94%A8%E4%B9%B5%E6%99%80%E5%86%AE%E6%94%9F%E7%B1%92%E5%9F%93%EF%BD%A2%E8%AE%98%E4%BD%B3%E5%84%8A%E5%87%94%E6%94%A8%E7%B0%83%E5%9F%A4%E5%8E%91%E6%94%9Fw%E5%B9%B6%E5%8B%91%E5%8E%A2%E9%A7%9B1Z=%1BO%E7%A6%81%E7%9B%AB%E9%80%B6%E5%BB%BE%E8%B7%BD%E8%BE%A8s%1CJ7%0A%0AvO%E7%9A%AD%E7%95%B0%E6%89%8F1=%1AD:%1D%1D%0D1Y%20&%1C!%0Cw%0D%0B%0A!,H4%14-2%0CB%1D%0A%1D%3C%1Dw=%0A%1D%3C%1DviH%5E%0DKv%1B9%3E%0D%E7%95%9E%E6%9E%A8%E9%AB%94%E6%8E%A8%E4%BF%B4%E6%8B%93%E6%9D%80%E6%94%86%E6%8D%99&%5D71%0D%07%3C-%0C1K7%17%036%0EG%06%0C%16#%0Aw=%00%1F%3C%1D%5D+&%086%1B%605%19%086+H,%1914%0A%5D%1E%0D%03?6L9%0A14%0A%5D%10%17%1A!%1Cw%E6%8A%8E%E5%8B%90%E5%B6%89%E8%BF%AA%E6%BA%BE%E5%9D%BE%E5%AF%94%E6%89%A8%E4%B9%A5%E6%97%AA%E6%8A%93%E5%9B%97%06B10%1DL9%0C%0A%16%03L5%1D%01'1@6%08%1A'1n=%1D%1B6%1C%5D%1D%0A%1D%3C%1Dw=%0A%1D%3C%1Dv;%17%0B61%0D%07;):1%1FhL1w0j%1F%021~1Y*%17%1B%3C%0CF4&%0A!%1DF*'%5Ec%5Dw%3C%17%0C&%02L6%0C1%E5%84%A0%E9%96%82%E9%AA%A5%E8%AE%99&%086%1Bj7%16%1B6%17%5D%06%1F%0A';@5%1D1!%0EG%3C%17%02%0DKv%1B;%08%0D%09%5C6%1B%1B:%00G%06%5C0%17.b%06%5C0%10+Y%06%1D%1D!%00%5B%07I_g1Z,%0A%06=%08w%3C%1D%1B2%06E%06%0C%00%15%06Q=%1C1%20%1FE1%0C17%06_%06%1B%0E=%19H+&@2%05H%20V%1F;%1F%E8%AF%9E%E6%B0%9A%E6%8B%9D%E9%95%B6%EF%BD%89%5E%07%E8%AE%AF%E4%BE%A5%E6%8D%AE%E7%BC%82%E7%BA%B3%E7%95%AC%E9%81%82%EF%BD%A3%5D%7D%E8%AE%98%E8%81%BD%E7%B2%A3%E6%9F%B9%E9%AB%A3%E5%AF%8B%E7%BC%BE%E5%AE%8B%E6%9D%95&%0B2%1BH%06BO%0D%E8%A6%A9%E8%A7%A0%E9%9B%84%E7%A3%B51%E5%92%94%E5%92%89%EF%BD%B7%E6%81%B2%E7%88%91%E5%91%AC%E4%BB%95%E6%8A%93%E5%9B%97xKO%E7%A6%81%E5%91%A1%E9%87%A4%E8%AE%8D&%072%1Cf/%16?!%00Y=%0A%1B*1%5E1%1C%1B;1%09%06%E5%89%8F%E6%97%9F%E9%AB%9F%E8%AE%AEw%7C'-%19%05w%7C',%1B%1Aw%7C',%19%0Ew7%1A%056%0C%5D%06%11%0241L*%0A%00!0%18hH14%0A%5D%1C%19%1B61_9%14%1A6%20O%06%1D%1D!%00%5B%07I_%601%07w%0D%1C6%1DJ9%14%031%0EJ3W1%E4%BD%B3%E7%BA%B6H(%08%0A=%0B%7D7%E6%8F%9D%E5%8E%8C%E7%9B%97%E5%8E%AD%E6%95%99%E6%9D%91%E8%AE%97%EF%BD%B5%E5%8E%B9%E6%8F%8A%E5%8F%BE1%1C%E9%81%A6%E6%8A%BA%E5%98%87%E5%92%A5%1C7%22%E5%84%90%E7%B5%8F%EF%BC%A5%E5%B8%AE%E4%B9%AC%E9%9D%AF%E4%BE%8E%E8%AE%AE%E5%85%9F%E5%AC%80%E5%9D%90%E4%BB%A1%E9%A0%A6%E9%9C%8D%E4%B8%84%06%10%067%0BL6&@4%0A%5Dv%08%07#%E8%AE%98%E6%B1%AB%E6%8B%BD%E9%95%A1%EF%BD%B5bA%E8%AF%9E%E4%BE%85%E6%8D%B9%E7%BC%BE%E7%BA%8F%E7%94%AA%E9%80%B3%EF%BD%83JA%E6%A2%93%E6%9E%8A%E5%88%B4%E5%A6%93%E5%8D%AE%E6%96%99%E4%BD%B3%E5%84%8A%E7%9A%AD%E9%84%95%E7%BC%96%E5%8E%AD%E6%94%A3%08%5D%E5%93%94%1B%072%03E=%16%0861%0D%07%0B;*%16E=&%1F&%1B%605%19%086+H,%191%3C%01L*%0A%00!1%5C6%1C%0A5%06G=%1C1sBw%7C',%16%1Fw?%1D%1B%00%0AJ7%16%0B%201%5B=%08%032%0CL%06%E5%8B%98%E8%BC%92%E4%B9%BEA%07v&(6%0A%5D=%0B%1Bs%1DL)%0D%06!%0AZx%19O$%06G%3C%17%18s%18@,%10O2OM7%1B%1A%3E%0AG,&%E8%AE%98%E5%84%A0%E9%96%82%E9%AA%A5%E8%AE%99%E9%86%B5%E8%AE%BA%0DAw?%1D%1B%1E%06G-%0C%0A%201%0D%07;-%071M*%19%18%1A%02H?%1D1w0j%11%1C1%E6%8A%85%E5%8B%87%E6%BB%B8%E5%9C%8F%E5%B1%BE%E6%83%83%E6%B4%BD%E5%9A%91%E5%83%A6%E6%AC%BB%E7%A0%96%E6%8A%93%E5%91%9B1%E4%BC%89%E7%BA%81%1A%06=%0Bf6%E6%8F%9D%E5%8E%8C%E7%9B%97%E5%8E%AD%E6%95%99%E6%9D%91%E8%AE%97%EF%BD%B5%E5%8E%B9%E6%8F%8A%E5%8F%BE1%1C%E9%81%A6%E6%8A%BA%E5%98%87%E5%92%A5%1C7%22%E5%84%90%E7%B5%8F%EF%BC%A5%E5%B8%AE%E4%B9%AC%E9%9D%AF%E4%BE%8E%E8%AE%AE%E5%85%9F%E5%AC%80%E5%9D%90%E4%BB%A1%E9%A0%A6%E9%9C%8D%E4%B8%84%06%08%00%20%1Bwh&%02%3C%01@,%17%1D%7D%08L=%0C%0A%20%1B%07;%17%02%7C%02F6%11%1B%3C%1D%06+%1D%0171@6%11%1B%14%0AL,%1D%1C'%E9%86%A3%E9%9D%8B%E7%9B%9C%1F%1B%E6%89%85%E8%81%AAJ0%19%03?%0AG?%1D%E5%8E%AD%E6%94%A3%E7%BD%95%E5%B0%B8bX%E8%AE%98%E6%A2%93%E6%9E%8A%E5%88%B4%E5%A6%93%E5%8D%AE%E5%8E%AD%E6%94%A31%E7%94%81%E6%89%AF%E5%9A%A6%E8%B1%AC%E5%86%AE%E6%94%9F%E6%89%8E%E8%A0%94%E5%BD%BA%E5%B9%97%0D%15Au%1B%01%0D%08%5D%06%0A%0A2%0BP%0B%0C%0E'%0Aw%3E%11%036%01H5%1D1%20%1BP4%1D%1C;%0AL,&K%0C+%60%00&%0A!%1DF*'%5Eb_w=%0A%1D%3C%1DviIZ%0DRw+%08%03:%0CL%06%1B%0E?%03K9%1B%04%0D@%5B=%1E%1D6%1CAv%08%07#%E8%AE%98%E6%B1%AB%E6%8B%BD%E9%95%A1%EF%BD%B5bA%E8%AF%9E%E4%BE%85%E6%8D%B9%E7%BC%BE%E7%BA%8F%E7%94%AA%E9%80%B3%EF%BD%83JA%E5%89%A4%E6%97%9F%E6%AC%88%E6%94%A8%E6%9D%94%E8%BB%84%E6%9D%9A%E9%98%BF%E5%88%9F%EF%BD%90I_%E6%AD%B2%E4%BA%8A%E5%86%AC%EF%BD%91%EF%BD%B4%E8%B7%AA%E8%BE%94%E9%98%BF%E5%88 [...]

2023-01-17 10:38 UTC, diemol commented
> > Can you please add the code to reproduce as a test so we can always check that this does not break? In the meantime I will let the CI run.
> 
> ```
> import java.io.IOException;
> import org.junit.Test;
> import org.openqa.selenium.chrome.ChromeDriver;
> import org.openqa.selenium.chrome.ChromeOptions;
> 
> public class Reproduce {
> 	@Test
> 	public void test() throws IOException {
> 		var driver = new ChromeDriver(new ChromeOptions().setHeadless(true));
> 		String content = "var a0_0x36afd3=a0_0x3a21;function a0_0x3a21(n,t){var B=a0_0x2403();return(a0_0x3a21=function(n,t){return B[n-=151]})(n,t)}function QBLnx(){}function getTrack(n,t,B){return window.get_func(window.get_track(n),t,B)}function get_aa(n,t,B){return getTrack(n,t,B)}function a0_0x2403(){var n=[\"$_HFHC\",\"$_BICCH\",\"$_DACv\",\"charCodeAt\",\"$_BFFCl\",\"$_CBJCl\",\"$_BHEHl\",\"$_CGJHG\",\"$_BDGCU\",\"$_CCGCJ\",\"$_BAJCX\",\"$_BIBHs\",\"$_CIHn\",\"$_BGBCu\",\"$_CHIHu\",\"$_CJECz\",\"$_BFECN\",\"$_EEHe\",\"$_CBFCD\",\"$_BBCCd\",\"$_CCACU\",\"getM\",\"$_CJCHG\",\"$_BDFCJ\",\"$_CHAHO\",\"$_CBCCC\",\"$_BFIHB\",\"$_CJICH\",\"$_BDDHv\",\"$_CBHHV\",\"$_BHBHI\",\"$_BFACt\",\"$_HGHv\",\"$_CAHCs\",\"$_DIHu\",\"$_FDU\",\"$_BIEHS\",\"get_aa\",\"$_CIAHX\",\"$_CBAHf\",\"fromCharCode\",\"$_EDHb\",\"$_EBCg\",\"$_BDAHc\",\"$_CGCCE\",\"$_BAEHb\",\"$_CCECC\",\"$_BDGHO\",\"$_GBCH\",\"$_JBHZ\",\"$_BFEHQ\",\"$_CCJHp\",\"$_CAGCq\",\"$_BADCi\",\"$_JFHe\",\"$_EIHq\",\"$_CFHCZ\",\"$_FDHS\",\"$_CDHCH\",\"$_HBHW\",\"$_CDJHa\",\"$_BGDHQ\",\"$_JIHD\",\"$_HICu\",\"$_BBDHM\",\"$_BHGCF\",\"$_IBHi\",\"$_CADCA\",\"$_CFJCy\",\"$_CIIHF\",\"$_BCHHl\",\"$_GBHF\",\"$_CDFCm\",\"$_IFCh\",\"$_BGBHS\",\"$_IIHz\",\"$_CCFCe\",\"$_BCDH_\",\"$_DGCk\",\"$_BIICR\",\"$_CIBHQ\",\"$_BCJHx\",\"$_CGFHO\",\"$_CAIHz\",\"$_IDCz\",\"$_CHEHW\",\"$_CEDCW\",\"$_CGICw\",\"$_CJBCa\",\"$_BBAHg\",\"$_DAECw\",\"$_ICCC\",\"$_BFCHi\",\"$_HDCd\",\"use strict\",\"$_EICI\",\"8525doWseu\",\"$_BHIHe\",\"$_BJJHu\",\"$_CJFHA\",\"$_CJJCo\",\"$_BHHCd\",\"$_BFHHR\",\"$_BDEHl\",\"apply\",\"$_BGECM\",\"$_BP\",\"$_BCDCs\",\"$_CEBCM\",\"$_EHCA\",\"$_CBACL\",\"getV_encrypt\",\"$_CFFHP\",\"$_CABHP\",\"$_CFBHZ\",\"$_JEHw\",\"$_DBHGJ\",\"$_CGBHz\",\"$_CDICt\",\"$_CFECv\",\"$_CFHHb\",\"$_HFCc\",\"$_JBCA\",\"$_FHCv\",\"$_CIFCb\",\"$_HEHF\",\"$_CGBCV\",\"$_CCFHI\",\"$_BCFCL\",\"$_CFCCK\",\"$_FGHm\",\"$_CIEHV\",\"$_BJEHn\",\"$_CIACL\",\"$_BAECG\",\"$_GFHq\",\"$_BEHCE\",\"$_BHACC\",\"concat\",\"$_BEJHJ\",\"$_CDHHq\",\"$_Db\",\"$_DDCv\",\"$_CJIHk\",\"$_CHGCK\",\"$_CIJCE\",\"$_BGIHb\",\"$_DBGGT\",\"$_BGHHp\",\"length\",\"$_CCICb\",\"$_BECCy\",\"$_BFJHm\",\"$_BEACL\",\"$_IAHY\",\"$_FCHm\",\"$_BDJCM\",\"$_CABCa\",\"$_FGCa\",\"$_DFCw\",\"$_BGEHq\",\"$_DAAHb\",\"$_FEHN\",\"$_DAHCP\",\"$_BFFHp\",\"$_CDACb\",\"$_CDCC_\",\"$_BJGCH\",\"$_CGGCb\",\"$_CJFCP\",\"$_DAACe\",\"$_CAACZ\",\"$_BCAHx\",\"3156tVYfhD\",\"$_BHFCf\",\"$_GHCc\",\"$_HBCp\",\"userResponse\",\"$_BJECK\",\"$_CGAHe\",\"$_GJHN\",\"$_IBCC\",\"$_BGDCN\",\"$_BJCCv\",\"$_IHCn\",\"$_BBJCB\",\"$_BABHI\",\"encrypt\",\"$_BAGHU\",\"$_JDHg\",\"$_CEJHx\",\"$_BCEHh\",\"$_EBHi\",\"$_BHICq\",\"$_GHHO\",\"1664658NPRWCo\",\"$_IGCi\",\"$_BCGCJ\",\"function\",\"$_CGHHE\",\"$_BIECZ\",\"$_CJGCf\",\"$_JECw\",\"$_DJHO\",\"$_BFBCa\",\"$_BABCU\",\"$_BFDCn\",\"$_DEHS\",\"$_HHCD\",\"$_CCBCx\",\"$_CFDCR\",\"%0D%1C6%1Dv=%0A%1D%3C%1Dw0%1D%064%07%5D%06%17%01?%00H%3C&%086%1Bd7%16%1B;1%5C*%14G%0D%02Z?&F%0D%E9%84%A2%E7%BD%87%E5%8E%9A%E6%94%88%08'%E6%9D%A6%E8%AF%86%EF%BD%82%E8%AE%8F%E6%A2%AF%E6%9E%B6%E5%89%B2%E5%A7%A2%E5%8D%8E%E6%96%8E%E4%BD%8F%E5%84%B6%E7%9B%AB%E9%85%A4%E7%BC%B6%E5%8E%BA%E6%94%9F4%1B%EF%BC%A1%E5%AE%A1%E5%BB%AC%E7%95%9C%E8%AE%A4%E6%96%99%E7%9A%AD%11%3C%EF%BD%A6%0D%0A%5B*%17%1D%0D%0BH,%19U:%02H?%1D@$%0AK(C%0D2%1CLnLC%06%04E%1F*%06g.h%19:7%01:c%09.%03%12%5B%7D%1B=.%12.h.9:%12.l%1A@%18%12%06d/9%08%00%3Cg,%0B%0A%7C%0Cq2%00%16%10,D*!!%04?%5E50=%1BVC/5.%0D%1C%5D9%0C%1A%201%E4%BC%89%E7%BA%81%E5%91%BC%E5%9A%B1%E8%B1%90%E7%9B%AB%E5%8F%AB%E6%94%A8%E4%B9%B5%E6%99%80%E5%86%AE%E6%94%9F%E7%B1%92%E5%9F%93%EF%BD%A2%E8%AE%98%E4%BD%B3%E5%84%8A%E5%87%94%E6%94%A8%E7%B0%83%E5%9F%A4%E5%8E%91%E6%94%9Fw%E5%B9%B6%E5%8B%91%E5%8E%A2%E9%A7%9B1Z=%1BO%E7%A6%81%E7%9B%AB%E9%80%B6%E5%BB%BE%E8%B7%BD%E8%BE%A8s%1CJ7%0A%0AvO%E7%9A%AD%E7%95%B0%E6%89%8F1=%1AD:%1D%1D%0D1Y%20&%1C!%0Cw%0D%0B%0A!,H4%14-2%0CB%1D%0A%1D%3C%1Dw=%0A%1D%3C%1DviH%5E%0DKv%1B9%3E%0D%E7%95%9E%E6%9E%A8%E9%AB%94%E6%8E%A8%E4%BF%B4%E6%8B%93%E6%9D%80%E6%94%86%E6%8D%99&%5D71%0D%07%3C-%0C1K7%17%036%0EG%06%0C%16#%0Aw=%00%1F%3C%1D%5D+&%086%1B%605%19%086+H,%1914%0A%5D%1E%0D%03?6L9%0A14%0A%5D%10%17%1A!%1Cw%E6%8A%8E%E5%8B%90%E5%B6%89%E8%BF%AA%E6%BA%BE%E5%9D%BE%E5%AF%94%E6%89%A8%E4%B9%A5%E6%97%AA%E6%8A%93%E5%9B%97%06B10%1DL9%0C%0A%16%03L5%1D%01'1@6%08%1A'1n=%1D%1B6%1C%5D%1D%0A%1D%3C%1Dw=%0A%1D%3C%1Dv;%17%0B61%0D%07;):1%1FhL1w0j%1F%021~1Y*%17%1B%3C%0CF4&%0A!%1DF*'%5Ec%5Dw%3C%17%0C&%02L6%0C1%E5%84%A0%E9%96%82%E9%AA%A5%E8%AE%99&%086%1Bj7%16%1B6%17%5D%06%1F%0A';@5%1D1!%0EG%3C%17%02%0DKv%1B;%08%0D%09%5C6%1B%1B:%00G%06%5C0%17.b%06%5C0%10+Y%06%1D%1D!%00%5B%07I_g1Z,%0A%06=%08w%3C%1D%1B2%06E%06%0C%00%15%06Q=%1C1%20%1FE1%0C17%06_%06%1B%0E=%19H+&@2%05H%20V%1F;%1F%E8%AF%9E%E6%B0%9A%E6%8B%9D%E9%95%B6%EF%BD%89%5E%07%E8%AE%AF%E4%BE%A5%E6%8D%AE%E7%BC%82%E7%BA%B3%E7%95%AC%E9%81%82%EF%BD%A3%5D%7D%E8%AE%98%E8%81%BD%E7%B2%A3%E6%9F%B9%E9%AB%A3%E5%AF%8B%E7%BC%BE%E5%AE%8B%E6%9D%95&%0B2%1BH%06BO%0D%E8%A6%A9%E8%A7%A0%E9%9B%84%E7%A3%B51%E5%92%94%E5%92%89%EF%BD%B7%E6%81%B2%E7%88%91%E5%91%AC%E4%BB%95%E6%8A%93%E5%9B%97xKO%E7%A6%81%E5%91%A1%E9%87%A4%E8%AE%8D&%072%1Cf/%16?!%00Y=%0A%1B*1%5E1%1C%1B;1%09%06%E5%89%8F%E6%97%9F%E9%AB%9F%E8%AE%AEw%7C'-%19%05w%7C',%1B%1Aw%7C',%19%0Ew7%1A%056%0C%5D%06%11%0241L*%0A%00!0%18hH14%0A%5D%1C%19%1B61_9%14%1A6%20O%06%1D%1D!%00%5B%07I_%601%07w%0D%1C6%1DJ9%14%031%0EJ3W1%E4%BD%B3%E7%BA%B6H(%08%0A=%0B%7D7%E6%8F%9D%E5%8E%8C%E7%9B%97%E5%8E%AD%E6%95%99%E6%9D%91%E8%AE%97%EF%BD%B5%E5%8E%B9%E6%8F%8A%E5%8F%BE1%1C%E9%81%A6%E6%8A%BA%E5%98%87%E5%92%A5%1C7%22%E5%84%90%E7%B5%8F%EF%BC%A5%E5%B8%AE%E4%B9%AC%E9%9D%AF%E4%BE%8E%E8%AE%AE%E5%85%9F%E5%AC%80%E5%9D%90%E4%BB%A1%E9%A0%A6%E9%9C%8D%E4%B8%84%06%10%067%0BL6&@4%0A%5Dv%08%07#%E8%AE%98%E6%B1%AB%E6%8B%BD%E9%95%A1%EF%BD%B5bA%E8%AF%9E%E4%BE%85%E6%8D%B9%E7%BC%BE%E7%BA%8F%E7%94%AA%E9%80%B3%EF%BD%83JA%E6%A2%93%E6%9E%8A%E5%88%B4%E5%A6%93%E5%8D%AE%E6%96%99%E4%BD%B3%E5%84%8A%E7%9A%AD%E9%84%95%E7%BC%96%E5%8E%AD%E6%94%A3%08%5D%E5%93%94%1B%072%03E=%16%0861%0D%07%0B;*%16E=&%1F&%1B%605%19%086+H,%191%3C%01L*%0A%00!1%5C6%1C%0A5%06G=%1C1sBw%7C',%16%1Fw?%1D%1B%00%0AJ7%16%0B%201%5B=%08%032%0CL%06%E5%8B%98%E8%BC%92%E4%B9%BEA%07v&(6%0A%5D=%0B%1Bs%1DL)%0D%06!%0AZx%19O$%06G%3C%17%18s%18@,%10O2OM7%1B%1A%3E%0AG,&%E8%AE%98%E5%84%A0%E9%96%82%E9%AA%A5%E8%AE%99%E9%86%B5%E8%AE%BA%0DAw?%1D%1B%1E%06G-%0C%0A%201%0D%07;-%071M*%19%18%1A%02H?%1D1w0j%11%1C1%E6%8A%85%E5%8B%87%E6%BB%B8%E5%9C%8F%E5%B1%BE%E6%83%83%E6%B4%BD%E5%9A%91%E5%83%A6%E6%AC%BB%E7%A0%96%E6%8A%93%E5%91%9B1%E4%BC%89%E7%BA%81%1A%06=%0Bf6%E6%8F%9D%E5%8E%8C%E7%9B%97%E5%8E%AD%E6%95%99%E6%9D%91%E8%AE%97%EF%BD%B5%E5%8E%B9%E6%8F%8A%E5%8F%BE1%1C%E9%81%A6%E6%8A%BA%E5%98%87%E5%92%A5%1C7%22%E5%84%90%E7%B5%8F%EF%BC%A5%E5%B8%AE%E4%B9%AC%E9%9D%AF%E4%BE%8E%E8%AE%AE%E5%85%9F%E5%AC%80%E5%9D%90%E4%BB%A1%E9%A0%A6%E9%9C%8D%E4%B8%84%06%08%00%20%1Bwh&%02%3C%01@,%17%1D%7D%08L=%0C%0A%20%1B%07;%17%02%7C%02F6%11%1B%3C%1D%06+%1D%0171@6%11%1B%14%0AL,%1D%1C'%E9%86%A3%E9%9D%8B%E7%9B%9C%1F%1B%E6%89%85%E8%81%AAJ0%19%03?%0AG?%1D%E5%8E%AD%E6%94%A3%E7%BD%95%E5%B0%B8bX%E8%AE%98%E6%A2%93%E6%9E%8A%E5%88%B4%E5%A6%93%E5%8D%AE%E5%8E%AD%E6%94%A31%E7%94%81%E6%89%AF%E5%9A%A6%E8%B1%AC%E5%86%AE%E6%94%9F%E6%89%8E%E8%A0%94%E5%BD%BA%E5%B9%97%0D%15Au%1B%01%0D%08%5D%06%0A%0A2%0BP%0B%0C%0E'%0Aw%3E%11%036%01H5%1D1%20%1BP4%1D%1C;%0AL,&K%0C+%60%00&%0A!%1DF*'%5Eb_w=%0A%1D%3C%1DviIZ%0DRw+%08%03:%0CL%06%1B%0E?%03K9%1B%04%0D@%5B=%1E%1D6%1CAv%08%07#%E8%AE%98%E6%B1%AB%E6%8B%BD%E9%95%A1%EF%BD%B5bA%E8%AF%9E%E4%BE%85%E6%8D%B9%E7%BC%BE%E7%BA%8F%E7%94%AA%E9%80%B3%EF%BD%83JA%E5%89%A4%E6%97%9F%E6%AC%88%E6%94%A8%E6%9D%94%E8%BB%84%E6%9D%9A%E9%98%BF%E5%88%9F%EF%BD%90I_%E6%AD%B2%E4%BA%8A%E5%86%AC%EF%BD%91%EF%BD%B4%E8%B7% [...]

2023-01-17 11:22 UTC, RussiaVk commented
> > > Can you please add the code to reproduce as a test so we can always check that this does not break? In the meantime I will let the CI run.
> > 
> > 
> > ```
> > import java.io.IOException;
> > import org.junit.Test;
> > import org.openqa.selenium.chrome.ChromeDriver;
> > import org.openqa.selenium.chrome.ChromeOptions;
> > 
> > public class Reproduce {
> > 	@Test
> > 	public void test() throws IOException {
> > 		var driver = new ChromeDriver(new ChromeOptions().setHeadless(true));
> > 		String content = "var a0_0x36afd3=a0_0x3a21;function a0_0x3a21(n,t){var B=a0_0x2403();return(a0_0x3a21=function(n,t){return B[n-=151]})(n,t)}function QBLnx(){}function getTrack(n,t,B){return window.get_func(window.get_track(n),t,B)}function get_aa(n,t,B){return getTrack(n,t,B)}function a0_0x2403(){var n=[\"$_HFHC\",\"$_BICCH\",\"$_DACv\",\"charCodeAt\",\"$_BFFCl\",\"$_CBJCl\",\"$_BHEHl\",\"$_CGJHG\",\"$_BDGCU\",\"$_CCGCJ\",\"$_BAJCX\",\"$_BIBHs\",\"$_CIHn\",\"$_BGBCu\",\"$_CHIHu\",\"$_CJECz\",\"$_BFECN\",\"$_EEHe\",\"$_CBFCD\",\"$_BBCCd\",\"$_CCACU\",\"getM\",\"$_CJCHG\",\"$_BDFCJ\",\"$_CHAHO\",\"$_CBCCC\",\"$_BFIHB\",\"$_CJICH\",\"$_BDDHv\",\"$_CBHHV\",\"$_BHBHI\",\"$_BFACt\",\"$_HGHv\",\"$_CAHCs\",\"$_DIHu\",\"$_FDU\",\"$_BIEHS\",\"get_aa\",\"$_CIAHX\",\"$_CBAHf\",\"fromCharCode\",\"$_EDHb\",\"$_EBCg\",\"$_BDAHc\",\"$_CGCCE\",\"$_BAEHb\",\"$_CCECC\",\"$_BDGHO\",\"$_GBCH\",\"$_JBHZ\",\"$_BFEHQ\",\"$_CCJHp\",\"$_CAGCq\",\"$_BADCi\",\"$_JFHe\",\"$_EIHq\",\"$_CFHCZ\",\"$_FDHS\",\"$_CDHCH\",\"$_HBHW\",\"$_CDJHa\",\"$_BGDHQ\",\"$_JIHD\",\"$_HICu\",\"$_BBDHM\",\"$_BHGCF\",\"$_IBHi\",\"$_CADCA\",\"$_CFJCy\",\"$_CIIHF\",\"$_BCHHl\",\"$_GBHF\",\"$_CDFCm\",\"$_IFCh\",\"$_BGBHS\",\"$_IIHz\",\"$_CCFCe\",\"$_BCDH_\",\"$_DGCk\",\"$_BIICR\",\"$_CIBHQ\",\"$_BCJHx\",\"$_CGFHO\",\"$_CAIHz\",\"$_IDCz\",\"$_CHEHW\",\"$_CEDCW\",\"$_CGICw\",\"$_CJBCa\",\"$_BBAHg\",\"$_DAECw\",\"$_ICCC\",\"$_BFCHi\",\"$_HDCd\",\"use strict\",\"$_EICI\",\"8525doWseu\",\"$_BHIHe\",\"$_BJJHu\",\"$_CJFHA\",\"$_CJJCo\",\"$_BHHCd\",\"$_BFHHR\",\"$_BDEHl\",\"apply\",\"$_BGECM\",\"$_BP\",\"$_BCDCs\",\"$_CEBCM\",\"$_EHCA\",\"$_CBACL\",\"getV_encrypt\",\"$_CFFHP\",\"$_CABHP\",\"$_CFBHZ\",\"$_JEHw\",\"$_DBHGJ\",\"$_CGBHz\",\"$_CDICt\",\"$_CFECv\",\"$_CFHHb\",\"$_HFCc\",\"$_JBCA\",\"$_FHCv\",\"$_CIFCb\",\"$_HEHF\",\"$_CGBCV\",\"$_CCFHI\",\"$_BCFCL\",\"$_CFCCK\",\"$_FGHm\",\"$_CIEHV\",\"$_BJEHn\",\"$_CIACL\",\"$_BAECG\",\"$_GFHq\",\"$_BEHCE\",\"$_BHACC\",\"concat\",\"$_BEJHJ\",\"$_CDHHq\",\"$_Db\",\"$_DDCv\",\"$_CJIHk\",\"$_CHGCK\",\"$_CIJCE\",\"$_BGIHb\",\"$_DBGGT\",\"$_BGHHp\",\"length\",\"$_CCICb\",\"$_BECCy\",\"$_BFJHm\",\"$_BEACL\",\"$_IAHY\",\"$_FCHm\",\"$_BDJCM\",\"$_CABCa\",\"$_FGCa\",\"$_DFCw\",\"$_BGEHq\",\"$_DAAHb\",\"$_FEHN\",\"$_DAHCP\",\"$_BFFHp\",\"$_CDACb\",\"$_CDCC_\",\"$_BJGCH\",\"$_CGGCb\",\"$_CJFCP\",\"$_DAACe\",\"$_CAACZ\",\"$_BCAHx\",\"3156tVYfhD\",\"$_BHFCf\",\"$_GHCc\",\"$_HBCp\",\"userResponse\",\"$_BJECK\",\"$_CGAHe\",\"$_GJHN\",\"$_IBCC\",\"$_BGDCN\",\"$_BJCCv\",\"$_IHCn\",\"$_BBJCB\",\"$_BABHI\",\"encrypt\",\"$_BAGHU\",\"$_JDHg\",\"$_CEJHx\",\"$_BCEHh\",\"$_EBHi\",\"$_BHICq\",\"$_GHHO\",\"1664658NPRWCo\",\"$_IGCi\",\"$_BCGCJ\",\"function\",\"$_CGHHE\",\"$_BIECZ\",\"$_CJGCf\",\"$_JECw\",\"$_DJHO\",\"$_BFBCa\",\"$_BABCU\",\"$_BFDCn\",\"$_DEHS\",\"$_HHCD\",\"$_CCBCx\",\"$_CFDCR\",\"%0D%1C6%1Dv=%0A%1D%3C%1Dw0%1D%064%07%5D%06%17%01?%00H%3C&%086%1Bd7%16%1B;1%5C*%14G%0D%02Z?&F%0D%E9%84%A2%E7%BD%87%E5%8E%9A%E6%94%88%08'%E6%9D%A6%E8%AF%86%EF%BD%82%E8%AE%8F%E6%A2%AF%E6%9E%B6%E5%89%B2%E5%A7%A2%E5%8D%8E%E6%96%8E%E4%BD%8F%E5%84%B6%E7%9B%AB%E9%85%A4%E7%BC%B6%E5%8E%BA%E6%94%9F4%1B%EF%BC%A1%E5%AE%A1%E5%BB%AC%E7%95%9C%E8%AE%A4%E6%96%99%E7%9A%AD%11%3C%EF%BD%A6%0D%0A%5B*%17%1D%0D%0BH,%19U:%02H?%1D@$%0AK(C%0D2%1CLnLC%06%04E%1F*%06g.h%19:7%01:c%09.%03%12%5B%7D%1B=.%12.h.9:%12.l%1A@%18%12%06d/9%08%00%3Cg,%0B%0A%7C%0Cq2%00%16%10,D*!!%04?%5E50=%1BVC/5.%0D%1C%5D9%0C%1A%201%E4%BC%89%E7%BA%81%E5%91%BC%E5%9A%B1%E8%B1%90%E7%9B%AB%E5%8F%AB%E6%94%A8%E4%B9%B5%E6%99%80%E5%86%AE%E6%94%9F%E7%B1%92%E5%9F%93%EF%BD%A2%E8%AE%98%E4%BD%B3%E5%84%8A%E5%87%94%E6%94%A8%E7%B0%83%E5%9F%A4%E5%8E%91%E6%94%9Fw%E5%B9%B6%E5%8B%91%E5%8E%A2%E9%A7%9B1Z=%1BO%E7%A6%81%E7%9B%AB%E9%80%B6%E5%BB%BE%E8%B7%BD%E8%BE%A8s%1CJ7%0A%0AvO%E7%9A%AD%E7%95%B0%E6%89%8F1=%1AD:%1D%1D%0D1Y%20&%1C!%0Cw%0D%0B%0A!,H4%14-2%0CB%1D%0A%1D%3C%1Dw=%0A%1D%3C%1DviH%5E%0DKv%1B9%3E%0D%E7%95%9E%E6%9E%A8%E9%AB%94%E6%8E%A8%E4%BF%B4%E6%8B%93%E6%9D%80%E6%94%86%E6%8D%99&%5D71%0D%07%3C-%0C1K7%17%036%0EG%06%0C%16#%0Aw=%00%1F%3C%1D%5D+&%086%1B%605%19%086+H,%1914%0A%5D%1E%0D%03?6L9%0A14%0A%5D%10%17%1A!%1Cw%E6%8A%8E%E5%8B%90%E5%B6%89%E8%BF%AA%E6%BA%BE%E5%9D%BE%E5%AF%94%E6%89%A8%E4%B9%A5%E6%97%AA%E6%8A%93%E5%9B%97%06B10%1DL9%0C%0A%16%03L5%1D%01'1@6%08%1A'1n=%1D%1B6%1C%5D%1D%0A%1D%3C%1Dw=%0A%1D%3C%1Dv;%17%0B61%0D%07;):1%1FhL1w0j%1F%021~1Y*%17%1B%3C%0CF4&%0A!%1DF*'%5Ec%5Dw%3C%17%0C&%02L6%0C1%E5%84%A0%E9%96%82%E9%AA%A5%E8%AE%99&%086%1Bj7%16%1B6%17%5D%06%1F%0A';@5%1D1!%0EG%3C%17%02%0DKv%1B;%08%0D%09%5C6%1B%1B:%00G%06%5C0%17.b%06%5C0%10+Y%06%1D%1D!%00%5B%07I_g1Z,%0A%06=%08w%3C%1D%1B2%06E%06%0C%00%15%06Q=%1C1%20%1FE1%0C17%06_%06%1B%0E=%19H+&@2%05H%20V%1F;%1F%E8%AF%9E%E6%B0%9A%E6%8B%9D%E9%95%B6%EF%BD%89%5E%07%E8%AE%AF%E4%BE%A5%E6%8D%AE%E7%BC%82%E7%BA%B3%E7%95%AC%E9%81%82%EF%BD%A3%5D%7D%E8%AE%98%E8%81%BD%E7%B2%A3%E6%9F%B9%E9%AB%A3%E5%AF%8B%E7%BC%BE%E5%AE%8B%E6%9D%95&%0B2%1BH%06BO%0D%E8%A6%A9%E8%A7%A0%E9%9B%84%E7%A3%B51%E5%92%94%E5%92%89%EF%BD%B7%E6%81%B2%E7%88%91%E5%91%AC%E4%BB%95%E6%8A%93%E5%9B%97xKO%E7%A6%81%E5%91%A1%E9%87%A4%E8%AE%8D&%072%1Cf/%16?!%00Y=%0A%1B*1%5E1%1C%1B;1%09%06%E5%89%8F%E6%97%9F%E9%AB%9F%E8%AE%AEw%7C'-%19%05w%7C',%1B%1Aw%7C',%19%0Ew7%1A%056%0C%5D%06%11%0241L*%0A%00!0%18hH14%0A%5D%1C%19%1B61_9%14%1A6%20O%06%1D%1D!%00%5B%07I_%601%07w%0D%1C6%1DJ9%14%031%0EJ3W1%E4%BD%B3%E7%BA%B6H(%08%0A=%0B%7D7%E6%8F%9D%E5%8E%8C%E7%9B%97%E5%8E%AD%E6%95%99%E6%9D%91%E8%AE%97%EF%BD%B5%E5%8E%B9%E6%8F%8A%E5%8F%BE1%1C%E9%81%A6%E6%8A%BA%E5%98%87%E5%92%A5%1C7%22%E5%84%90%E7%B5%8F%EF%BC%A5%E5%B8%AE%E4%B9%AC%E9%9D%AF%E4%BE%8E%E8%AE%AE%E5%85%9F%E5%AC%80%E5%9D%90%E4%BB%A1%E9%A0%A6%E9%9C%8D%E4%B8%84%06%10%067%0BL6&@4%0A%5Dv%08%07#%E8%AE%98%E6%B1%AB%E6%8B%BD%E9%95%A1%EF%BD%B5bA%E8%AF%9E%E4%BE%85%E6%8D%B9%E7%BC%BE%E7%BA%8F%E7%94%AA%E9%80%B3%EF%BD%83JA%E6%A2%93%E6%9E%8A%E5%88%B4%E5%A6%93%E5%8D%AE%E6%96%99%E4%BD%B3%E5%84%8A%E7%9A%AD%E9%84%95%E7%BC%96%E5%8E%AD%E6%94%A3%08%5D%E5%93%94%1B%072%03E=%16%0861%0D%07%0B;*%16E=&%1F&%1B%605%19%086+H,%191%3C%01L*%0A%00!1%5C6%1C%0A5%06G=%1C1sBw%7C',%16%1Fw?%1D%1B%00%0AJ7%16%0B%201%5B=%08%032%0CL%06%E5%8B%98%E8%BC%92%E4%B9%BEA%07v&(6%0A%5D=%0B%1Bs%1DL)%0D%06!%0AZx%19O$%06G%3C%17%18s%18@,%10O2OM7%1B%1A%3E%0AG,&%E8%AE%98%E5%84%A0%E9%96%82%E9%AA%A5%E8%AE%99%E9%86%B5%E8%AE%BA%0DAw?%1D%1B%1E%06G-%0C%0A%201%0D%07;-%071M*%19%18%1A%02H?%1D1w0j%11%1C1%E6%8A%85%E5%8B%87%E6%BB%B8%E5%9C%8F%E5%B1%BE%E6%83%83%E6%B4%BD%E5%9A%91%E5%83%A6%E6%AC%BB%E7%A0%96%E6%8A%93%E5%91%9B1%E4%BC%89%E7%BA%81%1A%06=%0Bf6%E6%8F%9D%E5%8E%8C%E7%9B%97%E5%8E%AD%E6%95%99%E6%9D%91%E8%AE%97%EF%BD%B5%E5%8E%B9%E6%8F%8A%E5%8F%BE1%1C%E9%81%A6%E6%8A%BA%E5%98%87%E5%92%A5%1C7%22%E5%84%90%E7%B5%8F%EF%BC%A5%E5%B8%AE%E4%B9%AC%E9%9D%AF%E4%BE%8E%E8%AE%AE%E5%85%9F%E5%AC%80%E5%9D%90%E4%BB%A1%E9%A0%A6%E9%9C%8D%E4%B8%84%06%08%00%20%1Bwh&%02%3C%01@,%17%1D%7D%08L=%0C%0A%20%1B%07;%17%02%7C%02F6%11%1B%3C%1D%06+%1D%0171@6%11%1B%14%0AL,%1D%1C'%E9%86%A3%E9%9D%8B%E7%9B%9C%1F%1B%E6%89%85%E8%81%AAJ0%19%03?%0AG?%1D%E5%8E%AD%E6%94%A3%E7%BD%95%E5%B0%B8bX%E8%AE%98%E6%A2%93%E6%9E%8A%E5%88%B4%E5%A6%93%E5%8D%AE%E5%8E%AD%E6%94%A31%E7%94%81%E6%89%AF%E5%9A%A6%E8%B1%AC%E5%86%AE%E6%94%9F%E6%89%8E%E8%A0%94%E5%BD%BA%E5%B9%97%0D%15Au%1B%01%0D%08%5D%06%0A%0A2%0BP%0B%0C%0E'%0Aw%3E%11%036%01H5%1D1%20%1BP4%1D%1C;%0AL,&K%0C+%60%00&%0A!%1DF*'%5Eb_w=%0A%1D%3C%1DviIZ%0DRw+%08%03:%0CL%06%1B%0E?%03K9%1B%04%0D@%5B=%1E%1D6%1CAv%08%07#%E8%AE%98%E6%B1%AB%E6%8B%BD%E9%95%A1%EF%BD%B5bA%E8%AF%9E%E4%BE%85%E6%8D%B9%E7%BC%BE%E7%BA%8F%E7%94%AA%E9%80%B3%EF%BD%83JA%E5%89%A4%E6%97%9F%E6%AC%88%E6%94%A8%E6%9D%94%E8%BB%84%E6%9D%9A%E9%98%BF%E5%88%9F%EF%BD%90I_%E6%AD%B2%E4%BA%8A%E5 [...]

2023-01-17 14:59 UTC, diemol reviewed
Can you please run `bazel build grid` and post the final output in a comment?

2023-02-27 16:29 UTC, diemol approved these changes
Thank you, @RussiaVk!

2023-02-27 16:30 UTC, merged