scrapped refactors from old PR
SeleniumHQ/selenium pull request #11907
Opened 2023-04-15 22:02 UTC by dev-ardi

**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

Apply refactors from https://github.com/SeleniumHQ/selenium/pull/11837

- I delete clone from config as it's not needed anymore 
- I change some owned types that don't need to be to references
- Pattern matching for str_to_os

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed. https://github.com/SeleniumHQ/selenium/issues/11906

2023-04-17 09:28 UTC, bonigarcia requested changes

2023-04-17 09:28 UTC, bonigarcia commented on rust/src/config.rs
> +    match os {
Please revert these changes. Currently, Selenium Manager is only compiled for Windows, macOS, and Linux. Moreover, panicking in not a good option, since all errors should properly logged through the logger (since the output of Selenium Manager is done in several options, such as JSON).

2023-04-17 09:51 UTC, dev-ardi commented on rust/src/config.rs
> +    match os {
I agree that we should not panic with user input, however I still believe it to be an error to pass any value other than the permitted ones. We can still add a fallback (` _ => LINUX`), however I don't think this should be allowed.

I leave it up to you to decide.

2023-04-17 09:55 UTC, bonigarcia commented on rust/src/config.rs
> +    match os {
My decision was clear: "Please revert these changes". And I gave you the reason why: Selenium Manager is only compiled for these three operating systems: Windows, macOS, and Linux.

2023-04-19 09:50 UTC, diemol commented
@dev-ardi would you like to continue working on this PR? We are about to do a release soon and wanted to know if we could have this as part of the release.

2023-04-19 10:07 UTC, dev-ardi commented
@diemol sure, it's a very minor PR but I can try to get some time and finish it today :)

2023-04-19 10:36 UTC, bonigarcia approved these changes

2023-04-19 10:37 UTC, bonigarcia approved these changes

2023-04-19 10:54 UTC, diemol approved these changes
Thank you, @dev-ardi!

2023-04-19 10:54 UTC, merged