[java] add more logging to Selenium Manager
SeleniumHQ/selenium pull request #11959
Opened 2023-04-27 12:18 UTC by titusfortner

### Description

* Changes log name to `log` which we want to make the standard in the rest of the project (future PR)
* Add `INFO` that about to use Selenium Manager
* Send `--verbose` to Selenium Manager if logging set to `FINE` or higher
* Add `FINE` for: 
    * Command executed
    * Driver Path being used
    * Any DEBUG lines of log 

### Motivation and Context

We need to be able to get more details about what problems users are having 
Also (at least while in Beta) we want users to know that Selenium Manager is being used.
We may want to change that from `INFO` to `FINE` after beta?

Ideally we have a section on Selenium Manager in our documentation that we can point to for explaining what it is doing and how to get more logging info, etc. But that's a future PR.

2023-05-01 02:18 UTC, titusfortner commented
Ah found the issue for this PR - #11642

2023-05-02 10:28 UTC, diemol requested changes
Left a suggestion

2023-05-02 10:28 UTC, diemol commented on java/src/org/openqa/selenium/manager/SeleniumManager.java
> +        commandList.add("--json");
```suggestion
        commandList.add("json");
```

2023-05-02 10:28 UTC, diemol commented on java/src/org/openqa/selenium/manager/SeleniumManager.java
> +        commandList.add("--json");
That is a value for the parameter not a parameter itself.

2023-05-02 15:38 UTC, titusfortner commented on java/src/org/openqa/selenium/manager/SeleniumManager.java
> +    private static final Logger log = Logger.getLogger(SeleniumManager.class.getName());
We have a lot more `LOG` than `log`, so I think we do want to use `LOG` here, I'll change it back

2023-05-02 16:52 UTC, diemol approved these changes

2023-05-02 18:51 UTC, merged