[rb][BiDi] Add Script module commands and types
SeleniumHQ/selenium pull request #12082
Opened 2023-05-22 18:26 UTC by TamsilAmani

### Description

Add script module commands and types

### Motivation and Context

Implement script module commands and types as described in https://w3c.github.io/webdriver-bidi/#module-script.
The majority of classes and interfaces are mapping the common data types as described in https://w3c.github.io/webdriver-bidi/#data-types.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2023-05-22 18:28 UTC, TamsilAmani commented
I have to add one more test for `this` parameter. I will add it shortly. Also, the work for `add/remove preload script` will be pushed in a separate PR.

2023-05-22 23:42 UTC, p0deje reviewed
That's quite a lot of code, any chance we could avoid all the type mapping and just rely on native Ruby types? I understand that not every type exists, but I am not sure when those would be needed as-is? For instance, is there any reason why someone would prefer a returned `EvaluateResultException` object instead of raised Ruby exception? The latter allows leveraging regular Ruby `being ... rescue .. ned` to handle exceptions, rather than check for the returned object class.

2023-05-23 00:28 UTC, titusfortner commented
Yeah, this is a lot of strict typing for Ruby. There is no compile time error checking, so there's less need for all the "enums" and type wrappers. Unless it needs to be processed, it's probably better to just return things as Hashes.

2023-05-23 02:52 UTC, TamsilAmani commented
Ok. So I'll try to remove custom-defined classes/objects where possible. I am inclined to go with what is mentioned in w3c spec hence creating those classes. I will push the commit with relevant changes soon. Thank you @titusfortner and @p0deje

2023-06-22 19:11 UTC, TamsilAmani commented
@p0deje @titusfortner 
Changes made as per the suggestions. Now I am giving the response to the user as it is. No wrapping into object for now.

2023-10-26 13:20 UTC, titusfortner approved these changes

2023-10-26 14:11 UTC, titusfortner requested changes
Ruby shouldn't be enforcing types this way. We need a better approach for it

2024-07-12 09:04 UTC, diemol commented
Are we ever merging this?

2025-03-31 20:20 UTC, closed without merging