Extract original driver from decorated driver when Augmenting a driver
SeleniumHQ/selenium pull request #12248
Opened 2023-06-23 12:35 UTC by baflQA

**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description
Extract the original driver from the decorated driver.

### Motivation and Context
When trying to use the Augmentor on a decorated driver, the extractRemoteWebDriver method will be executed infinitely. 

### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-06-23 16:45 UTC, diemol reviewed
Thanks for this PR.

Is there a way we can reproduce the issue first to understand the fix? Maybe it can be added as a test?

2023-06-24 13:12 UTC, baflQA commented
> Thanks for this PR.
> 
> Is there a way we can reproduce the issue first to understand the fix? Maybe it can be added as a test?

I will be happy to add a test, once I'm finished with indexing the project 😂 it was running the whole night and crashed my IDE at some point...

2023-06-25 15:18 UTC, titusfortner commented
Make sure you mark as excluded all the `bazel-*` directories and the `build` directory. InteliJ hates indexing Bazel generated things for some reason.

2023-06-26 16:20 UTC, baflQA commented
> Make sure you mark as excluded all the `bazel-*` directories and the `build` directory. InteliJ hates indexing Bazel generated things for some reason.

That helped a lot! Thx

2023-06-26 16:35 UTC, titusfortner commented
You have *no idea how long it took me to figure out what was causing the problem...

2023-06-27 19:03 UTC, diemol requested changes

2023-06-27 19:03 UTC, diemol commented on java/src/org/openqa/selenium/support/BUILD.bazel
> +        "//java/src/org/openqa/selenium/support/decorators",
Can you please leave this in order? Should go after `events`.

2023-06-27 19:03 UTC, diemol commented on java/src/org/openqa/selenium/support/decorators/BUILD.bazel
> +        "//java/src/org/openqa/selenium/remote:__subpackages__",
Can you please leave this in order? Should go before the `/test/` one.

2023-06-28 11:58 UTC, diemol approved these changes
Thank you, @baflQA!

2023-06-28 14:37 UTC, merged