[py] Update timeouts.py docstrings
SeleniumHQ/selenium pull request #12523
Opened 2023-08-08 23:54 UTC by palmermbandy

**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description
Updated the docstrings in `py/selenium/webdriver/common/timeouts.py` to fix some typos and add descriptions for each attribute of the `Timeouts` class (I used the corresponding descriptions from `rb/lib/selenium/webdriver/common/timeouts.rb`).

### Motivation and Context
Ensure accurate and informative docstrings.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-08-08 23:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SeleniumHQ/selenium?pullRequest=12523) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SeleniumHQ/selenium?pullRequest=12523) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SeleniumHQ/selenium?pullRequest=12523) it.</sub>

2023-08-14 19:01 UTC, titusfortner requested changes
I love adding the w3c link to the docs, thanks for renaming the implicit_timeout since it was inconsistent. I think best practice for docstrings is to be regular english? I'm not an expert, but seems more descriptive to say "script execution timeout" and "page load timeout on navigation" etc etc

2023-08-14 19:01 UTC, titusfortner commented on py/selenium/webdriver/common/timeouts.py
> +    """Sets and Gets the value of page_load:
I think these should all be English not code (e.g., "page load timeout")

2023-08-14 20:14 UTC, AutomatedTester commented on py/selenium/webdriver/common/timeouts.py
> +    """Sets and Gets the value of page_load:
Agreed. This should be for humans to read. They won't know what `page_load` means

2023-08-15 00:00 UTC, palmermbandy commented on py/selenium/webdriver/common/timeouts.py
> +    """Sets and Gets the value of page_load:
👍 I'll update these.

2023-08-15 02:01 UTC, titusfortner approved these changes

2023-08-15 03:51 UTC, isaulv commented
This should be good to go.

2023-08-15 11:47 UTC, merged

2023-08-15 11:47 UTC, titusfortner commented
@palmermbandy thank you!