Update fragment.bzl to fix a bug where "_" was overwritten
SeleniumHQ/selenium pull request #12704
Opened 2023-09-07 21:24 UTC by mdmintz

Update fragment.bzl to fix a bug where ``_`` was overwritten

This resolves https://github.com/SeleniumHQ/selenium/issues/12659

This reverts https://github.com/SeleniumHQ/selenium/pull/12557

### Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)

### Checklist

- [X] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.

2023-09-07 23:54 UTC, titusfortner requested changes
We should keep the text that was deleted as well. Can you run git revert on it?

2023-09-13 20:14 UTC, asolntsev approved these changes

2023-09-14 13:53 UTC, merged

2024-06-13 10:11 UTC, Jabbar2010 commented
Hi, @mdmintz @titusfortner @jarib @KazuCocoa there is an error on my side,
<img width="1114" alt="image" src="https://github.com/SeleniumHQ/selenium/assets/11782524/c60f9c22-3f4d-47e6-b2f6-5752a0c09fa5">
 I found the root cause is from atoms, as this PR, you just add navigator and document from window, but no JSON
<img width="1792" alt="image" src="https://github.com/SeleniumHQ/selenium/assets/11782524/1c9949a8-0fdf-413e-9256-df6f68b2f028">
<img width="743" alt="image" src="https://github.com/SeleniumHQ/selenium/assets/11782524/b159c0e7-8589-4f04-baf0-d40bbd2f5ae0">
Besides above, I also found some other apis not passed into the inner function, such as window.Range...
So do you know how to resolve my issue? and you can take a look at my another linked issue: https://github.com/appium/appium-remote-debugger/issues/383, we also have the "_" override because of this.Is there a good way to fix it?

2024-06-13 10:32 UTC, Jabbar2010 commented
Sorry, updated: https://github.com/appium/appium-remote-debugger/issues/383#issuecomment-2165253340