[rust] update log messages
SeleniumHQ/selenium pull request #12754
Opened 2023-09-15 22:13 UTC by titusfortner

### Description
* change a logging from warn to debug
* add message to an error

### Motivation and Context
* since "avoid browser downloads" is the default, we should not throw warning
* when we throw a warning we should give the suggestion for the fix

This is why I'm wondering if it makes sense to call this something else other than offline mode, because I'm not sure this message always applies. What do you think?

2023-09-15 22:25 UTC, diemol requested changes

2023-09-15 22:25 UTC, diemol commented on rust/src/lib.rs
> +pub const OFFLINE_REQUEST_ERR_MSG: &str = "Unable to discover proper {} version in offline mode; run grid node with --selenium-manager true";
This is already displayed in the Grid. No need to change it here.

2023-09-15 22:25 UTC, diemol commented on rust/src/main.rs
> +            log.debug("Offline flag set, but also asked not to avoid browser downloads. Honouring offline flag");
Yes, this is what I wanted to change a while ago.

2023-09-16 01:56 UTC, titusfortner commented
Cool, I just committed the one change, and I'll close this

2023-09-16 01:56 UTC, closed without merging