[java] ensure proper error message gets logged
SeleniumHQ/selenium pull request #12853
Opened 2023-10-02 19:15 UTC by titusfortner

Java Throwable class (at least for Java 11) does not set the detailMessage in the `initCause` method the same way it does in the way it does in the constructor:

```
    public Throwable(Throwable cause) {
        fillInStackTrace();
        detailMessage = (cause==null ? null : cause.toString());
        this.cause = cause;
    }
```
vs

```
    public synchronized Throwable initCause(Throwable cause) {
        if (this.cause != this)
            throw new IllegalStateException("Can't overwrite cause with " +
                                            Objects.toString(cause, "a null"), this);
        if (cause == this)
            throw new IllegalArgumentException("Self-causation not permitted", this);
        this.cause = cause;
        return this;
    }
```

2023-10-03 19:39 UTC, diemol requested changes

2023-10-03 19:39 UTC, diemol commented on java/src/org/openqa/selenium/remote/http/WebSocket.java
> +      if(message == null && cause.getCause().getMessage() != null) {
```suggestion
      if (message == null && cause.getCause().getMessage() != null) {
```

2023-10-03 19:39 UTC, diemol commented on java/src/org/openqa/selenium/remote/http/WebSocket.java
> +      if(message == null && cause.getCause().getMessage() != null) {
Can `cause.getCause()` be `null`?

2023-10-04 00:27 UTC, titusfortner commented on java/src/org/openqa/selenium/remote/http/WebSocket.java
> +      if(message == null && cause.getCause().getMessage() != null) {
Maybe? It doesn't error, it just doesn't log anything.

2023-10-04 12:24 UTC, titusfortner commented on java/src/org/openqa/selenium/remote/http/WebSocket.java
> +      if(message == null && cause.getCause().getMessage() != null) {
oh. `getCause()`, misunderstood because was reading from my phone. Might as well protect against it.

2023-10-05 12:12 UTC, pujagani commented
Good observation. This is a good start. I think similar changes might be required in other places as well. Example: https://github.com/SeleniumHQ/selenium/blob/c64ed7d067f8314b2d3fbe3600dcc1ed47b866a4/java/src/org/openqa/selenium/devtools/DevToolsException.java#L25, https://github.com/SeleniumHQ/selenium/blob/c64ed7d067f8314b2d3fbe3600dcc1ed47b866a4/java/src/org/openqa/selenium/bidi/BiDiException.java#L25

2023-10-05 13:17 UTC, titusfortner commented
@diemol I updated the code to make sure `getCause()` isn't null. It doesn't matter if `getMessage()` is null, it will just end up in the same place, but if `getCause()` were null for some reason, then... NPE.

2023-10-05 13:48 UTC, titusfortner commented
@pujagani I wanted to keep the changes limited to the one place I saw a specific problem (missing info in the logs I'm looking at). The code is still the same in Java 21, which leads me to believe it is intentional? I raised a ticket with Oracle to get their response.

> We will review your report and have assigned it an internal review ID : 9076067. Depending upon the completeness of the report and our ability to reproduce the problem, either a new bug will be posted, or we will contact you for further information.

🤷

2023-10-05 16:25 UTC, diemol approved these changes

2023-10-05 22:12 UTC, merged