Cargo.lock: Update ring and required crates for riscv support
SeleniumHQ/selenium pull request #13194
Opened 2023-11-23 22:23 UTC by jsmolic

Cargo.lock: Update ring and required crates for riscv support

### Description
Selenium-webdriver fails to compile on RISC-V due to outdated version of ring used (https://bugs.gentoo.org/912999).
Ring has added RISC-V support in
https://github.com/briansmith/ring/pull/1627, so update ring and additional necessary crates to allow us to build on RISC-V. This change was compile tested inside a virtual machine.

### Types of changes

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist
- [ x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x ] All new and existing tests passed.

2023-11-23 22:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SeleniumHQ/selenium?pullRequest=13194) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SeleniumHQ/selenium?pullRequest=13194) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SeleniumHQ/selenium?pullRequest=13194) it.</sub>

2023-11-25 13:36 UTC, titusfortner commented
The lockfile should be auto generated, don't we need to change something in another file to ensure this is used?

2023-11-27 10:40 UTC, bonigarcia requested changes
Indeed, the `Cargo.lock` is automatically updated by Cargo when there is some change in `Cargo.toml`. So, I don't see the point of updating the lock file individually. In summary, I think this PR is incomplete or incorrect.

2023-11-28 15:36 UTC, closed without merging

2023-11-28 15:36 UTC, jsmolic commented
I understand now, since ring is indirect dependency here it needs to be fixed in the source of package which is actually depending on ring. Apologies for jumping to conclusion that it should be changed in selenium, I will close this PR.
Thank you for your input!

2023-11-28 16:10 UTC, titusfortner commented
I suspect we can require a different version of a transitive dependency, depending on how it is set up? It just needs to be in a different file.

2023-11-29 16:46 UTC, jsmolic commented
The dependency chain goes like this: selenium -> reqwest -> hyper-rustls -> rustls -> ring and the culprit seems to be hyper-rustls; it doesn''t use the latest version of rustls which pulls in the correct version of ring that compiles on risc-v.
Is there any way we can pin the rustls version?

2023-11-29 17:35 UTC, titusfortner commented
@AutomatedTester or @bonigarcia can you comment on how transitive rust dependencies work?

2023-11-30 09:04 UTC, bonigarcia commented
There is plenty of online information about that:

https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html
https://stackoverflow.com/questions/27770031/how-do-i-pin-indirect-dependencies-of-a-crate