use subprocess.DEVNULL instead of open(os.devnull) to avoid leaking a…
SeleniumHQ/selenium pull request #13329
Opened 2023-12-18 14:59 UTC by graingert

… file handle

**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

### Motivation and Context

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [ ] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-12-18 14:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SeleniumHQ/selenium?pullRequest=13329) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SeleniumHQ/selenium?pullRequest=13329) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SeleniumHQ/selenium?pullRequest=13329) it.</sub>

2023-12-19 08:42 UTC, diemol requested changes
Can you please make the linter happy and I can merge this:

```
  import os
 import time
 from platform import system
-from subprocess import STDOUT, DEVNULL
+from subprocess import DEVNULL
+from subprocess import STDOUT
 from subprocess import Popen
```

https://github.com/SeleniumHQ/selenium/actions/runs/7249860032/job/19771842820?pr=13329#step:5:24

2023-12-19 09:29 UTC, graingert commented on py/selenium/webdriver/firefox/firefox_binary.py
> +from subprocess import STDOUT, DEVNULL
```suggestion
from subprocess import DEVNULL
from subprocess import STDOUT
```

2023-12-19 10:23 UTC, diemol approved these changes
Thank you, @graingert!

2023-12-19 10:23 UTC, merged