Node WebSocket not working with sub-path option
SeleniumHQ/selenium pull request #13407
Opened 2024-01-08 04:06 UTC by vietnd96

**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description
[java] Update subPath for ProxyNodeWebsockets

### Motivation and Context
Fix issue #13393 - WebSocket at `ws://ip:port/selenium-grid/sessions/{ID}/se/vnc` with `selenium-grid` is the `sub-path`

---
Some info on the fix
- In `NodeOptions` added method `getSubPath()` to extract the subPath, which can be set from config `sub-path` (in `[network] section` or from config `grid-url` / `hub` (in `[node]` section)
- In `ProxyNodeWebsockets`, subPath is removed from request URI before matching UrlTemplate

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2024-01-08 04:18 UTC, krmahadevan commented on java/src/org/openqa/selenium/grid/node/config/NodeFlags.java
> +  public String subPath;
@vietnd96 - Can you please let me know what would the application behaviour be in the below scenario? 

1. Hub was started with the sub path as "/foo"
2. Node1 is now being started with the sub-path as "/bar"
3. Node2 is now being started with the sub-path as "foobar"

So does this mean that a testcase would need to know the sub-path using which the node (to which the session was routed to) was spun off, in order for it to be able to access the web sockets?

2024-01-08 10:17 UTC, diemol requested changes
The Node should not need changes, the Router/Hub should be in charge of forwarding the WebSocket message to the Node and that is it. The client does not have direct access to Nodes, which is why we should not change the Nodes at all.

2024-01-08 19:36 UTC, vietnd96 commented
> The Node should not need changes, the Router/Hub should be in charge of forwarding the WebSocket message to the Node and that is it. The client does not have direct access to Nodes, which is why we should not change the Nodes at all.

@diemol Yes, the client does not have direct access to Nodes. The change is only for Router/Hub forwarding the `ProxyNodeWebsockets`.
The Router/Hub forwarding request e.g `/subPath/session/{id}/se/vnc`. In `ProxyNodeWebsockets` there are some UrlTemplate matching to open particular Ws, and the problem is there. When matching e.g req `/subPath/session/{id}/se/vnc` vs template `/session/{id}/se/vnc` it returned not match, which caused the Ws not open correctly.
In NodeOptions, at least `grid-url` or `hub` is required always for Node register to Router/Hub, user can pass the Grid URL within subPath from the config. In Node, only there is `getGridSubPath()` to extract the subPath from Router/Hub URL and set it to `ProxyNodeWebsockets` for matching UrlTemplate as well as construct the URLs for se:vnc, cdp, bidi, fwd in session capabilities, which is used to establish Ws
I have renamed the method to `getGridSubPath`, hope that avoid the confusion that we are trying to allow users to set subPath for Nodes to access directly from outside.

2024-01-09 09:32 UTC, diemol approved these changes

2024-01-09 09:33 UTC, diemol commented
> > The Node should not need changes, the Router/Hub should be in charge of forwarding the WebSocket message to the Node and that is it. The client does not have direct access to Nodes, which is why we should not change the Nodes at all.
> 
> @diemol Yes, the client does not have direct access to Nodes. The change is only for Router/Hub forwarding to `ProxyNodeWebsockets`. The Router/Hub forwarding request e.g `/subPath/session/{id}/se/vnc`. In `ProxyNodeWebsockets` there are some UrlTemplate matching to open particular Ws, and the problem is there. When matching e.g req `/subPath/session/{id}/se/vnc` vs template `/session/{id}/se/vnc` it returned not match, which caused the Ws not open correctly. In NodeOptions, at least `grid-url` or `hub` is required always for Node register to Router/Hub, user can pass the Grid URL within subPath from the config. In Node, only there is `getGridSubPath()` to extract the subPath from Router/Hub URL and set it to `ProxyNodeWebsockets` for matching UrlTemplate as well as construct the URLs for se:vnc, cdp, bidi, fwd in session capabilities, which is used to establish Ws I have renamed the method to `getGridSubPath`, hope that avoid the confusion that we are trying to allow users to set subPath for Nodes to access directly from outside.

Understood, thank you. It makes sense.

2024-01-09 09:33 UTC, merged