fix: For security purposes, remove the output of Capabilities information from the logs.
SeleniumHQ/selenium pull request #13710
Opened 2024-03-20 03:44 UTC by zhangwt-cn

Fixes #13648

### Description
For security purposes, remove the output of Capabilities information from the logs.

### Motivation and Context
fix  #13648

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist
- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2024-03-20 03:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SeleniumHQ/selenium?pullRequest=13710) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SeleniumHQ/selenium?pullRequest=13710) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SeleniumHQ/selenium?pullRequest=13710) it.</sub>

2024-03-20 03:47 UTC, krmahadevan commented
@zhangwt-cn - Not everyone would want this to be the default behaviour no? What if this were to be behind a flag, which when flipped will give this behaviour? 

Either way, I would wait to hear from @diemol before you take up the recommendation of obfuscating the capabilities for security reasons.

2024-03-20 03:58 UTC, zhangwt-cn commented
@krmahadevan Users should have the capability to produce their own logs, and I believe that the output of sensitive information should not come from the logs of the underlying framework.

2024-03-20 04:01 UTC, krmahadevan commented
> @krmahadevan Users should have the capability to produce their own logs, and I believe that the output of sensitive information should not come from the logs of the underlying framework.

Sure. But the point of contention is as to what does and what does not denote/represent as sensitive information. For majority of the users, they aren't packing in any sensitive data into the capabilities. The capabilities itself does not have any such information apart from the browser version and the optional flags that are being passed to the underlying driver. So there's no reason as to why this needs to be hidden out from the regular user. It looks to me that you are adding additional stuff into the capabilities object which you wouldn't want to be logged. That was why I am suggesting that this behaviour be controlled via a flag which can be toggled (It should be switched off by default)

2024-03-20 04:16 UTC, zhangwt-cn commented
> > @krmahadevan Users should have the capability to produce their own logs, and I believe that the output of sensitive information should not come from the logs of the underlying framework.
> 
> Sure. But the point of contention is as to what does and what does not denote/represent as sensitive information. For majority of the users, they aren't packing in any sensitive data into the capabilities. The capabilities itself does not have any such information apart from the browser version and the optional flags that are being passed to the underlying driver. So there's no reason as to why this needs to be hidden out from the regular user. It looks to me that you are adding additional stuff into the capabilities object which you wouldn't want to be logged. That was why I am suggesting that this behaviour be controlled via a flag which can be toggled (It should be switched off by default)

Okay, I understand what you mean. I'll make some adjustments based on your suggestions.

2024-03-20 04:36 UTC, krmahadevan commented
@zhangwt-cn  Please hold on. Lets hear from @diemol before you make any changes. I would like to ensure that you spend more time on this based on his inputs. I was just throwing in my thoughts.

2024-03-20 09:24 UTC, diemol requested changes
Thank you for starting to work on this, @zhangwt-cn!

I agree with @krmahadevan. Not all users want this to be the default behavior. As an example, this information helps debug as well.

The fix could be to obfuscate any given capability or a pattern (e.g., `wss://admin:admin@org-se...`), which should be under a flag and configuration.

2024-03-21 07:05 UTC, zhangwt-cn commented
Added a `privacyMode` attribute to control whether to output the following sensitive information.
- se:vnc
- se:cdp

Users can utilize the `privacyMode` attribute to control whether or not to output certain types of sensitive information, such as
```java
FirefoxOptions options = new FirefoxOptions();
options.setCapability("privacyMode", false);
```
If privacyMode is true, then it will display *******, if it is false, it will display the real content.
@diemol @krmahadevan

2024-03-21 09:37 UTC, diemol requested changes
I believe this would not work because:
- `privacyMode` is not a [W3C capability](https://www.w3.org/TR/webdriver1/#capabilities), so it would be filtered and ignored.
- This change modifies the capability value, and we only want to obfuscate it. The client bindings must use the actual value to connect to the server.

We probably want a configuration on the server side that enables or disables the obfuscation, following the same pattern we use through flags and options: https://github.com/SeleniumHQ/selenium/tree/trunk/java/src/org/openqa/selenium/grid/distributor/config

2024-03-21 09:44 UTC, zhangwt-cn commented
> I believe this would not work because:
> 
> * `privacyMode` is not a [W3C capability](https://www.w3.org/TR/webdriver1/#capabilities), so it would be filtered and ignored.
> * This change modifies the capability value, and we only want to obfuscate it. The client bindings must use the actual value to connect to the server.
> 
> We probably want a configuration on the server side that enables or disables the obfuscation, following the same pattern we use through flags and options: https://github.com/SeleniumHQ/selenium/tree/trunk/java/src/org/openqa/selenium/grid/distributor/config

Okay, I will make some modifications.

2024-03-21 16:19 UTC, shs96c commented on java/src/org/openqa/selenium/SharedCapabilitiesMethods.java
> +  private static final Set<String> PRIVACY_KEYS;
We now target Java 11+, so it's okay to use `Set.of("se:vnc", "se:cdp")`

2024-03-22 07:45 UTC, zhangwt-cn commented
@diemol Based on your advice, I made the following changes
```java
public class DistributorOptions {
  public static boolean PRIVACY_MODE = true;

  private final Config config;

  public DistributorOptions(Config config) {
    this.config = config;
    PRIVACY_MODE = getPrivacyMode();
  }
  public boolean getPrivacyMode() {
    return config
      .getBool(DISTRIBUTOR_SECTION, "privacy-mode")
      .orElse(PRIVACY_MODE);
  }
}
```
```java
public class DistributorFlags implements HasRoles {
 @Parameter(
    names = "--privacy-mode",
    description = "If privacy-mode is true, then sensitive information will display *******, if it is false, it will display the real content. ")
  @ConfigValue(section = DISTRIBUTOR_SECTION, name = "privacy-mode", example = "true")
  private boolean privacyMode = PRIVACY_MODE;
}
```
but I encountered a problem: `SharedCapabilitiesMethods` cannot access `DistributorOptions`. It seems that changing dependencies is necessary, but I'm unsure if such changes are allowed, or if you have any better suggestions.

2025-05-29 10:21 UTC, closed without merging