[dotnet] implement WebDriver BiDi with WebDriverBiDi dependency
SeleniumHQ/selenium pull request #14052
Opened 2024-05-29 21:20 UTC by titusfortner

Status
This is in Draft so we can discuss what the API could look like
Tests pass locally, but not on CI because I can't figure out how to wire in all the bazel things when adding a dependency
Note that it is using #14051 as the base to make the comparison of the implementation easier

### Description
* Adds the WebDriver BiDi package dependency from Jim
* BiDi is disabled in tests by default
* Starts a BiDi session if `webSocketUrl` is set
* Implements all the Navigation commands with conditionals for whether BiDi is present
* Implements PageLoadStrategy waits

### Motivation and Context
This should be the easiest way to have working BiDi implementation in .NET since Jim has already written all the lower level commands (and would love not to duplicate that effort if we don't have to)
The conditionals in each method are not the most elegant, but they are straightforward, and I think that's preferred.
It'll be easy enough to just remove the conditionals (and probably the Sync methods as well) when we remove support for WebDriver classic (likely Selenium 6)

### Considerations
This sidesteps updating `browsingContextId` from context changes; we'll handle that separately
Still need to figure out how to tag the tests that use BiDi and have a separate run to run those both with BiDi enabled and disabled

attn: @YevgeniyShunevych

2024-05-30 07:16 UTC, nvborisenko requested changes
We should not introduce new external dependencies.

2024-12-26 22:20 UTC, diemol commented
@nvborisenko I believe this PR does not make sense anymore, correct?

2024-12-27 11:46 UTC, nvborisenko commented
This PR can be considered as actual when it starts using of our BiDi implementation. For me it is interesting how we are going to spread BiDi Driver instance across downstream classes (like `Navigator` class).

2025-06-20 19:18 UTC, nvborisenko commented
Now we have own implementation.

2025-06-20 19:18 UTC, closed without merging

2025-06-20 19:32 UTC, nvborisenko commented
And ask me, together we will find the best approach.