[py] Don't override browser options with desired capabilities by defa…
SeleniumHQ/selenium pull request #6814
Opened 2019-01-04 12:09 UTC by carlosgcampos

…ult in WebKitGTK

When desired_capabilities parameter is omitted in WebKitGTK driver, the
default capabilities are used. If options are also passed they are
updated from desired capabilities, overriding the passed options. The
desired_capabalities parameter should default to None instead.

- [ ] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

2019-01-04 14:05 UTC, lmtierney requested changes

2019-01-04 14:05 UTC, lmtierney commented on py/selenium/webdriver/webkitgtk/webdriver.py
> +from .options import Options
Can you address the flake8 error here? Then we can merge.

2019-01-04 15:51 UTC, merged

2019-01-04 15:51 UTC, lmtierney commented
Merged, thank you!

2023-06-19 10:03 UTC, bphd commented
WebKitGTK is now the only browser that can't run without any options, producing an error asking about desired capabilities. Is that because of you?

2023-06-19 12:11 UTC, titusfortner commented
@bphd please file a bug report if you believe the code is not doing what it should.