Move create connection logic to redis package
SeleniumHQ/selenium pull request #8487
Opened 2020-07-07 08:24 UTC by raju249

**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

### Motivation and Context

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [ ] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2020-07-07 09:02 UTC, shs96c requested changes

2020-07-07 09:02 UTC, shs96c commented on java/server/src/org/openqa/selenium/redis/RedisClientHelper.java
> +public class RedisClientHelper {
From the point of view of our system, this _is_ the redis client, or (perhaps) the connection. Name the class after what it does in our system and why it's special. Names like `Helper`, `Utility`, `Support` and `Impl` all fail to clearly explain the actual role the class is fulfilling, and so should be avoided.

2020-07-07 09:02 UTC, shs96c commented on java/server/src/org/openqa/selenium/redis/RedisClientHelper.java
> +  public void close() {
Looks like we should be implementing `Closable` or `AutoClosable`

2020-07-08 21:42 UTC, diemol approved these changes
LGTM 👍

2020-07-08 21:42 UTC, merged