Add a(n E2E) test for basic (left) arrow key usage
SeleniumHQ/selenium pull request #8492
Opened 2020-07-09 10:20 UTC by haqer1

Fixes: #8483

**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description
Helps ensure that Selenium supports basic (left) arrow key usage

### Motivation and Context
I used this to determine that the issue i've worked around stems from Quill(JS.com), rather than Selenium

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md) document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2020-07-09 12:24 UTC, AutomatedTester requested changes

2020-07-09 12:24 UTC, AutomatedTester commented on java/client/test/org/openqa/selenium/interactions/BasicKeyboardInterfaceTest.java
> +    driver.get("https://google.com/ncr");
Can you add a new html page to `common/src/web` and use that instead

2020-07-09 12:24 UTC, AutomatedTester commented on java/client/test/org/openqa/selenium/interactions/BasicKeyboardInterfaceTest.java
> +  static final String LEFT_ARROW_SPACE_TEST_STRING_CORE = "bfmtv";
Add these to the test method so it's all together

2020-07-09 14:41 UTC, AutomatedTester commented
just going to wait for travis before merging

2020-07-09 14:46 UTC, haqer1 commented
> just going to wait for travis before merging

Cool.

P.S. FYI, i re-used _single_text_input.html_ (re-use of code that already exists is frequently the best thing to do, & seems to be the case for the page aspect here).

2020-07-10 12:39 UTC, AutomatedTester approved these changes

2020-07-11 00:15 UTC, diemol approved these changes
Thank you for your contribution @haqer1!

2020-07-11 00:15 UTC, merged