Update RemoteWebElement.cs
SeleniumHQ/selenium pull request #8540
Opened 2020-07-16 04:00 UTC by DvoryadkinPavel

fix for https://github.com/SeleniumHQ/selenium/issues/8457

**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

### Motivation and Context

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [ ] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2020-07-16 04:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SeleniumHQ/selenium?pullRequest=8540) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SeleniumHQ/selenium?pullRequest=8540) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SeleniumHQ/selenium?pullRequest=8540) it.</sub>

2020-07-16 11:29 UTC, AutomatedTester requested changes
Could you please improved the commit message as it doesn't describe what is happening in the change. Imagine if you look at the git history and only see `Update filename.cs`

2020-07-16 11:29 UTC, AutomatedTester commented on dotnet/src/webdriver/Remote/RemoteWebElement.cs
> +            text = String.Join("\n",fileNames);
This line seems unneeded

2020-07-17 03:13 UTC, DvoryadkinPavel commented on dotnet/src/webdriver/Remote/RemoteWebElement.cs
> +            text = String.Join("\n",fileNames);
agreed

2020-07-17 03:41 UTC, DvoryadkinPavel commented on dotnet/src/webdriver/Remote/RemoteWebElement.cs
> +            text = String.Join("\n",fileNames);
PR title changed: took from issue

2020-07-17 07:21 UTC, DvoryadkinPavel commented
> Could you please improved the commit message as it doesn't describe what is happening in the change. Imagine if you look at the git history and only see `Update filename.cs`

Done

2020-07-17 11:05 UTC, AutomatedTester approved these changes

2020-07-17 13:28 UTC, AutomatedTester commented
Thanks for your PR. In future please update the commit message, as asked, and not just the PR title.

2020-07-17 13:29 UTC, merged