Improve the error messages output by some ExpectedConditions.
SeleniumHQ/selenium pull request #8630
Opened 2020-08-14 00:51 UTC by eschoeffler

### Description
attributeContains was incorrectly reporting the current value as "null". This
change fixes that.
textToBePresentInElement was not reporting the actual element text. This change
adds the actual element text in the failure message.

### Motivation and Context
I was writing selenium tests and having trouble debugging them because of the poor output of the existing ExpectedConditions logic. This change provides more useful output for failing tests.

### Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
Fixes bug with attributeContains condition error message.
- [X] New feature (non-breaking change which adds functionality)
Adds more useful error message for testToBePresentInElement condition.
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist
- [X ] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X ] I have added tests to cover my changes.
- [X ] All new and existing tests passed.

2020-08-14 00:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SeleniumHQ/selenium?pullRequest=8630) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SeleniumHQ/selenium?pullRequest=8630) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SeleniumHQ/selenium?pullRequest=8630) it.</sub>

2020-08-15 10:10 UTC, shs96c requested changes
Presumably, this is because you're doing matching against a very long piece of text (maybe the body element?) and the output of the existing class is hard to read. However, some people rely on the existing functionality, so eliding in all cases isn't correct. 

I'd suggest having an (optional) parameter for a maximum string length, preserving the existing signatures to ensure that people updating don't need to recompile their code.

2020-08-15 10:10 UTC, shs96c commented on java/client/src/org/openqa/selenium/support/ui/ExpectedConditions.java
> +      private String elementText = null;
Each `ExpectedCondition` implements `java.util.Function` These are expected to be stateless. This condition will leak previous `elementText` on the second usage, which doesn't seem ideal.

2020-09-10 21:26 UTC, diemol reviewed
@eschoeffler would you like to follow the suggestion in the previous review? Please let us know.

2020-12-22 23:14 UTC, diemol commented
Closing this PR as we did not get more input from the OP.

2020-12-22 23:14 UTC, closed without merging