Add disable escaping option for json parsing. Fix string escaping for event-logs.
SeleniumHQ/selenium pull request #9038
Opened 2021-01-13 11:36 UTC by pujagani

**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

Add disable escaping option for json parsing. 

### Motivation and Context

The event-logs attributes like session payload and capabilities leverage the built-in json parse to convert the objects to json strings. By default, the escape characters are included in the string. It resulted in inconsistent log string with some fields having escape characters and some being printed normally. The changes added, fix this by adding a disable escaping option. 

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [X] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

2021-01-17 12:39 UTC, shs96c requested changes
I'm not sure making the JSON encoder non-conformant is the right approach to follow for this problem. AIUI, we're passing in a json-encoded string to a logger, and then that's being escaped again. Perhaps we should investigate why we're doing the json escaping instead?

2021-01-17 12:39 UTC, shs96c commented on java/client/src/org/openqa/selenium/json/JsonOutput.java
> -  private static final Map<Integer, String> ESCAPES;
Prefer keeping this static block and setting a boolean for escaping if we're heading down this route.

2021-01-17 12:39 UTC, shs96c commented on java/client/src/org/openqa/selenium/json/JsonOutput.java
> +  private void setEscapes() {
Doing this per-json encoder is wasteful.

2021-01-23 20:01 UTC, barancev commented
Can you please demonstrate what logging issue we're trying to solve by this change?

2021-01-25 09:03 UTC, pujagani commented
Thank you for the review. Closing this PR in lieu of investigating the escaped string sent to the logger for event-logs.

2021-01-25 09:03 UTC, closed without merging

2021-01-25 12:28 UTC, pujagani commented
The logs currently are printed as follows: 
`{"traceId": "fc2964f4b3934af0a48df04e812acf5b","spanId": "dc660fec12498442","spanKind": "INTERNAL","eventTime": 1611575427636017843,"eventName": "Session request received by the distributor","attributes": {"logger": "org.openqa.selenium.grid.distributor.local.LocalDistributor","request.payload": "{\n  \"desiredCapabilities\": {\n    \"browserName\": \"chrome\"\n  },\n  \"capabilities\": {\n    \"firstMatch\": [\n      {\n        \"browserName\": \"chrome\"\n      }\n    ]\n  }\n}"}}` 

The reason is we leverage OpenTelemetry events and event attributes to display event-logs. Since, OpenTelemetry only accepts a string for an attribute value, for objects like payload and capabilities, we convert them to json string and add as an even-attribute. When the log statement is created, the fields from the span and events are added to a map and converted to a json string. Thus, object strings are escaped twice. The PR was aiming to as disable escaping option for such cases.