added new methods for RelativeBy(withXpath,withCssSelector) and added…
SeleniumHQ/selenium pull request #9273
Opened 2021-03-12 17:21 UTC by JustasMonkev

… tests for these methods

**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

added new methods for RelativeBy(withXpath,withCssSelector)

### Description
Added new Methods for RelativeLocator to improve UX. 

### Motivation and Context

I believe it improves UX. now it's easier to use RelativeLocator.  

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x ] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ x] My change requires a change to the documentation.
- [ -] I have updated the documentation accordingly.
- [ x] I have added tests to cover my changes.
- [ x] All new and existing tests passed.

2021-03-12 17:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SeleniumHQ/selenium?pullRequest=9273) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SeleniumHQ/selenium?pullRequest=9273) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SeleniumHQ/selenium?pullRequest=9273) it.</sub>

2021-03-18 11:02 UTC, shs96c requested changes
Hi! Thank you for the PR! I love the idea behind it, and it's going to be really helpful, but I think we should consider just passing in a general locator (a `By` subclass) to be even more useful. What do you think? That'd mean replacing `withTagName(String)` with `with(By)`

2021-03-18 11:02 UTC, shs96c commented on java/client/test/org/openqa/selenium/support/locators/RelativeLocatorTest.java
> +    List<WebElement> elements = driver.findElements(withXpath("//p").above(lowest));
The xpath locators rooted with `//` will (because of how xpath works) scan the entire document. My expectation with this is that we'll end up returning the first `p` tag in the entire doc. I'm surprised this works as expected....

2021-03-18 11:02 UTC, shs96c commented on java/client/test/org/openqa/selenium/support/locators/RelativeLocatorTest.java
> +    List<WebElement> seen = driver.findElements(withXpath("//td").above(By.id("center")).toRightOf(By.id("second")));
Again, this should be returning the very first `td` in the document.

2021-03-18 11:02 UTC, shs96c commented on java/client/src/org/openqa/selenium/support/locators/RelativeLocator.java
> +  public static RelativeBy withXpath(String xpathExpression) {
It may be better to just allow someone to pass in an arbitrary locator at this point. That is, replace `withTagName(String)` with `with(By)` so folks can write `with(tagName("td"))` or whatever takes their fancy.

2021-03-20 09:52 UTC, JustasMonkev commented on java/client/test/org/openqa/selenium/support/locators/RelativeLocatorTest.java
> +    List<WebElement> elements = driver.findElements(withXpath("//p").above(lowest));
should I use this xpath //p[position()=1]?

2021-03-20 17:03 UTC, JustasMonkev commented
please take a look @shs96c

2021-03-23 10:19 UTC, shs96c approved these changes
Hi! This looks great. Thank you for working on it :) There's a couple of things that we can clean up, but it won't take long to do that, and I'll make the changes once this is landed.

2021-03-23 10:19 UTC, shs96c commented on java/client/src/org/openqa/selenium/support/locators/RelativeLocator.java
> +  public static By tagName(String tagName) {
These can all be safely removed now that `with(By)` exists. People can use a static import to get a short `tagName` method call to allow `with(tagName("foo"))`

2021-03-23 10:19 UTC, shs96c commented
LGTM, and I think this will make using the relative locators a lot nicer. Thank you!

2021-03-23 10:20 UTC, merged