fix some typos, mostly in Java code
SeleniumHQ/selenium pull request #9937
Opened 2021-10-15 17:58 UTC by asolntsev

### Description
Just fixed some typos in comments and tests.

2021-10-20 03:32 UTC, titusfortner requested changes
Thanks for going through all of this. 

I'm much more comfortable fixing up comments and test names than actual code variables, but I don't see anything obviously wrong other than the two places where you missed updating an html element reference.

Also I don't think we want to make any changes to files in `third_party/`, `thoughtworks/` and the dojo js files, so please revert those.

2021-10-20 03:32 UTC, titusfortner commented on common/src/web/readOnlyPage.html
> +<input id="textInputNotEnabled" type="text" disabled="true" value="Test"/>
You missed updating this in .NET test
https://github.com/SeleniumHQ/selenium/blob/64447d4b03f6986337d1ca8d8b6476653570bcc1/dotnet/test/common/ClearTest.cs#L22

2021-10-20 03:32 UTC, titusfortner commented on common/src/web/readOnlyPage.html
> +<textarea rows="5" id="textAreaNotEnabled" disabled="true" cols="20">
missed a reference in .NET https://github.com/SeleniumHQ/selenium/blob/64447d4b03f6986337d1ca8d8b6476653570bcc1/dotnet/test/common/ClearTest.cs#L49

2021-10-21 06:50 UTC, asolntsev commented on common/src/web/readOnlyPage.html
> +<textarea rows="5" id="textAreaNotEnabled" disabled="true" cols="20">
Thank you for the correction, @titusfortner !
I really missed .NET part :)

2021-10-21 07:00 UTC, closed without merging

2021-10-21 07:18 UTC, asolntsev commented
superseded by https://github.com/SeleniumHQ/selenium/pull/9964