IEDriver NewWindow3 API workaround solution for Edge IEMode
SeleniumHQ/selenium pull request #9950
Opened 2021-10-18 21:04 UTC by guangyuexu

IEDriver NewWindow3 API workaround solution for Edge IEMode

### Description
This PR is to provide a workaround solution for IEDriver to track new created windows in Edge IEMode. 

### Motivation and Context
When IEDriver drives IE browser, there is a [NewWindow3 ](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/aa768288(v=vs.85)) API to help create new window and keep these new created window on track. 

When IEDriver drives Edge browser in IEMode, there is no such NewWindow3 API in Edge Browser. This PR is to create a workaround solution to help IEDriver track new created windows in Edge IEMode without using the NewWindow3 API. 

### Types of changes
Note that when Edge runs in IEMode, all IE windows are wrapped by an Edge window. That means, every IE window is a child window of a Edge window. It is possible to keep track of all IE window handles before and after a new window created. By comparing the window handles before after a new window event, the new window handles created from client side JS codes can be identified and tracked in IEDriver.

2021-10-22 20:01 UTC, jimevans requested changes

2021-10-22 20:01 UTC, jimevans commented on cpp/iedriver/Browser.cpp
> +BOOL CALLBACK FindIEBrowserHandles(HWND hwnd, LPARAM arg) {
Seems like these methods would be better located with their similar ones in `BrowserFactory.cpp`, no? I mean, I'm certainly not wedded to that, and we can always refactor locations later, I suppose.

2021-10-22 20:01 UTC, jimevans commented on cpp/iedriver/Browser.cpp
> +    ::PostMessage(this->executor_handle(), WD_BEFORE_NEW_WINDOW, NULL, NULL);
Seems like both `PostMessage` calls should be outside the `if` and `else` blocks here, along with `std::vector<HWND>* ie_window_handles = NULL;`, and setting `ie_window_handles` to the vector in the `if` case. But I'm being nitpicky, and I could be wrong.

2021-10-22 20:01 UTC, jimevans commented on cpp/iedriver/Browser.cpp
> +    for (auto& ewh : edge_window_handles) {
I dislike the use of `auto` here, if only because it's inconsistent with every other part of the code base. I know it's syntactic sugar that makes the creation of an iterator unnecessary, and if you push back on its use, I'm sure I'll cave, but consistency is a valid consideration.

2021-10-22 20:01 UTC, jimevans commented on cpp/iedriver/IECommandExecutor.cpp
> +      std::unordered_set<HWND> current_window_set(
Any particular reason for using `unordered_set` here, instead of just another vector? Not a criticism, just curious. I mean, I know the semantics are slightly different, but

2021-10-22 20:01 UTC, jimevans commented on cpp/iedriver/IECommandExecutor.cpp
> +        HWND new_window_window = diff[0];
This code all looks right for attaching to a browser instance. Nicely done.

2021-10-22 20:40 UTC, bwalderman reviewed
LGTM with some suggestions.

2021-10-22 20:40 UTC, bwalderman commented on cpp/iedriver/BrowserFactory.cpp
> -  executable_and_url.append(L" --ie-mode-force");
Why is this removed?

2021-10-22 20:40 UTC, bwalderman commented on cpp/iedriver/Browser.cpp
> +    for (auto& ewh : edge_window_handles) {
I think using `auto` and/or a reference `&` would be debatable if the elements were a more complex type, but HWNDs are just integers, so I think we can just use `HWND` here (and in the other places in this change where HWNDs are being iterated).

2021-10-22 22:55 UTC, guangyuexu commented on cpp/iedriver/Browser.cpp
> +BOOL CALLBACK FindIEBrowserHandles(HWND hwnd, LPARAM arg) {
Moved `FindIEBrowserHandles` and `FindEdgeBrowserHandles` functions to `BrowserFactory` as static methods. I also removed the similar function in class `IECommandExecutor`.

2021-10-22 22:56 UTC, guangyuexu commented on cpp/iedriver/Browser.cpp
> +    ::PostMessage(this->executor_handle(), WD_BEFORE_NEW_WINDOW, NULL, NULL);
Move the two `PostMessage` calls to the outside of the `if` and `else` blocks.

2021-10-22 22:57 UTC, guangyuexu commented on cpp/iedriver/Browser.cpp
> +    for (auto& ewh : edge_window_handles) {
Replaced `auto` with `HWND` in the changes.

2021-10-22 23:14 UTC, guangyuexu commented on cpp/iedriver/IECommandExecutor.cpp
> +      std::unordered_set<HWND> current_window_set(
This is for performance consideration. In case we have lots of window handles, it will be faster using `unordered_set` than `vector` to find out a new window handle from a large set of window handles.

2021-10-22 23:15 UTC, guangyuexu commented on cpp/iedriver/BrowserFactory.cpp
> -  executable_and_url.append(L" --ie-mode-force");
Brought `--ie-mode-force` switch back in this [commit](https://github.com/SeleniumHQ/selenium/pull/9950/commits/a2882488c2a296a3fd3fdc10636e33001315ea80).

2021-10-25 13:46 UTC, jimevans approved these changes
LGTM. Will merge ASAP.

2021-10-25 13:57 UTC, merged